- app/less/main_megamenu.less
Errors because of auto-formatting of comments that broke the less compiling
> fixed main_megamenu.less for compiling

- _config.yml
- docs/4.0/getting-started/introduction.md
- package-lock.json
> Documentation - Add jquery full version to our get started

- docs/4.0/components/dropdowns.md
- docs/4.0/components/popovers.md
- docs/4.0/components/tooltips.md
> Add information about boosted.bundle.js file

- js/tests/visual/carousel.html
- js/tests/visual/collapse.html
- js/tests/visual/modal.html
- js/tests/visual/o-megamenu.html
- js/tests/visual/o-navbar.html
I saw some errors on your visual tests 
/CC @Lausselloic
> Fix visual tests

- scss/_o-scroll-up.scss
There might be other things to ignore from RTLCSS…
> Using RTLCSS ignore rule for #95

- scss/_o-carousel.scss
- site/docs/4.3/components/carousel.md
- site/docs/4.3/components/custom-carousel.md
- site/docs/4.3/examples/orange-homepage/index.html
- site/docs/4.3/examples/orange-homepage/sample.css
Changes:
- Removing old swiper code in homepage in Examples.
- Unsetting the position of the pagination and reduicing the height of the custom carousel
> Fix examples template

- README.md
Links to CONTRIBUTING.md are broken in README.
> fix: links to CONTRIBUTING.md

- README.md
- site/_includes/footer.html
Netlify badging all the things.
> feat(README): add Netlify badge on both README and homepage's footer

- .github/workflows/test.yml
> chore(actions): get Bundlesize + BrowserStack + Coveralls actions back

- build/vnu-jar.js
- scss/_variables.scss
- scss/utilities/_background.scss
- scss/utilities/_text.scss
- site/_data/brand-colors.yml
- site/_data/colors.yml
- site/_data/theme-colors.yml
- site/docs/4.4/about/brand.md
- site/docs/4.4/assets/scss/_colors.scss
- site/docs/4.4/getting-started/accessibility.md
- site/docs/4.4/getting-started/theming.md
- site/docs/4.4/utilities/colors.md
New section for colour palette: http://boosted.netlify.com/docs/4.4/getting-started/theming/#brand-colors
> [Brand] — Colour palette

- _config.yml
- build/rollup.config.js
- bundlesize.config.json
- js/src/index.js
- site/_includes/docs-navbar.html
- site/_includes/header.html
- site/_includes/scripts.html
- site/docs/4.4/essentials/content-panel/index.html
- site/docs/4.4/essentials/footer/index.html
- site/docs/4.4/essentials/global-headers/index.html
- site/docs/4.4/essentials/product-details/index.html
- site/docs/4.4/essentials/quick-links/index.html
- site/docs/4.4/examples/administration-edition-page/index.html
- site/docs/4.4/examples/administration-main-page/index.html
- site/docs/4.4/examples/dashboard-orange-branded/index.html
- site/docs/4.4/examples/news-template/index.html
- site/docs/4.4/examples/orange-form/index.html
- site/docs/4.4/examples/orange-grid/index-fluid.html
- site/docs/4.4/examples/orange-grid/index.html
- site/docs/4.4/examples/orange-homepage/index.html
- site/docs/4.4/examples/pricing/index.html
- site/docs/4.4/getting-started/contents.md
- site/docs/4.4/getting-started/download.md
- site/docs/4.4/getting-started/introduction.md
There's also a few scripts loading improvements on the website part.
Can revert some commits if required by reviewers :100:
> Bundle focus visibility & improve wesbite performances

- bundlesize.config.json
- scss/_reboot.scss
- scss/_transitions.scss
- scss/_variables.scss
- scss/mixins/_transition.scss
- site/docs/4.4/assets/scss/docs.scss
Based on my own PR to Bootstrap : https://github.com/twbs/bootstrap/pull/29870
> Allow transition disabling fine tuning

- .github/workflows/notify.yml
> Bottermost

- scss/_o-tabs.scss
Also closes #336 since `o-tabs.js` is used :)
> [o-tabs] — arrow icons size & position

- .github/workflows/test.yml
- bundlesize.config.json
- js/src/o-megamenu.js
- js/tests/index.html
- js/tests/karma.conf.js
- package-lock.json
- package.json
- scss/_o-megamenu.scss
- site/docs/4.4/components/orange-megamenu.md
- site/docs/4.4/examples/news-template/index.html
> Megamenu fixes

- js/tests/karma.conf.js
- js/tests/unit/o-megamenu.js
- scss/_o-megamenu.scss
> Megamenu defaults

- scss/mixins/_forms.scss
> Feedback icons got shrinked

- site/docs/4.4/components/toasts.md
> Translucent toasts

- js/src/o-megamenu.js
- js/src/o-navbar.js
- js/src/o-priority-nav.js
- js/src/o-scroll-up.js
- js/src/o-tab.js
To follow Bootstrap conventions.
> Switch to string constant

- scss/_o-tablesorter.scss
> fix(tablesorter): reverse asc/desc icon

- scss/_breadcrumb.scss
> Ensure breadcrumbs items are underlined

- scss/_navbar.scss
> Dropdown & icons alignment in navbar-nav

- scss/_pagination.scss
- scss/_variables.scss
> Pagination items contrasts on focus

- scss/_modal.scss
- scss/_variables.scss
- site/docs/4.5/components/modal.md
> Modal sizes

- scss/_carousel.scss
> Ensure img in carousels are 100% wide

- js/src/button.js
> Ensure focus-visible is used on toggle buttons

- scss/_buttons.scss
- scss/_variables.scss
- site/docs/4.5/components/buttons.md
> .btn-icon sizes

- NOTICE.txt
- scss/orangeHelvetica.scss
- site/docs/4.5/getting-started/introduction.md
- site/docs/4.5/getting-started/rtl.md
> Licence wording and update NOTICE.txt

- scss/_variables.scss
> Increase spacings to ease list-group alignment

- build/docs-rtl.js
- site/docs/4.5/essentials/footer/index.html
- site/docs/4.5/essentials/global-headers/index.html
- site/docs/4.5/examples/administration-edition-page/index.html
- site/docs/4.5/examples/administration-main-page/index.html
- site/docs/4.5/examples/dashboard-orange-branded/index.html
- site/docs/4.5/examples/news-template/index.html
- site/docs/4.5/examples/orange-form/index.html
- site/docs/4.5/examples/orange-homepage/index.html
update docs-rtl script to manage production build
update jquery sri in sample pages
> Fix doc rtl and jquery sri

- NOTICE.txt
- scss/_pagination.scss
- scss/_variables.scss
- scss/orange-helvetica.scss
- site/content/docs/5.0/getting-started/introduction.md
Fixes #412 
Backports #301 #427 #428 to v5
> chore(backport v4-dev): #301 #427 #428

- scss/_pagination.scss
- scss/_variables.scss
> Add default vertical margins to pagination

- scss/utilities/_text.scss
> Drop important to follow up text-emphasis-variant() evolution

- nuget/boosted.nuspec
- nuget/boosted.sass.nuspec
update copy year, fix icon and add repo url
> update nuspec files

- site/docs/4.5/components/orange-footer.md
Remove white space in orange footer example
> Remove white space

- scss/_button-group.scss
- scss/_pagination.scss
- scss/_reboot.scss
- scss/_variables.scss
Backport relevant `v4-dev` changes to v5.
> v4-dev backports

- site/docs/4.5/components/modal.md
> Update Orange popin example

- scss/_input-group.scss
- scss/_variables.scss
> Input group various fixes

- scss/_o-step-bar.scss
- scss/_variables.scss
> Smaller margin between stepbar items

- scss/_spinners.scss
Closes  #299
See [Bootstrap #31882](https://github.com/twbs/bootstrap/pull/31882) for official support upstream.
> Reduced motion spinners

- scss/_o-tabs.scss
> Ensure o-tabs aren't underlined

- scss/_o-megamenu.scss
> Ensure top position for submenus

- scss/_variables.scss
- scss/mixins/_grid.scss
> Ensure small gutters depends on main gutters

- js/tests/karma.conf.js
- scss/boosted-grid.scss
- scss/mixins/_grid.scss
- site/docs/4.5/components/navbar.md
> Start to deprecate things in v4 to ease switching to v5

- scss/_alert.scss
> fix(alerts): ensure content don't overlap icon

- .github/workflows/percy.yml
- build/.pa11yci.json
- site/assets/scss/_component-examples.scss
- site/assets/scss/_syntax.scss
- site/content/docs/5.0/getting-started/introduction.md
Fixes #567
Previews:
— HTML code examples: https://deploy-preview-589--boosted.netlify.app/docs/5.0/getting-started/introduction/
— SCSS code examples: https://deploy-preview-589--boosted.netlify.app/docs/5.0/customize/sass/
— JS code examples: https://deploy-preview-589--boosted.netlify.app/docs/5.0/components/collapse/#via-javascript
~~**Note to myself**: [some of our colors](https://v5-dev--boosted.netlify.app/docs/5.0/customize/color/#all-colors) might provide sufficient contrasts against white whilst being most contrasted against black.~~
> Syntax highlighting contrasts

- scss/_functions.scss
- scss/_variables.scss
- site/assets/scss/_component-examples.scss
- site/assets/scss/_syntax.scss
Closes #567 
Backport from #589
> Backport syntax highlighting contrasts

- .bundlewatch.config.json
- scss/_carousel.scss
- scss/_o-carousel.scss
- scss/_variables.scss
> Carousel controls and indicators, Orange branded

- .bundlewatch.config.json
- scss/_type.scss
- scss/_variables.scss
- site/assets/scss/_boosted.scss
- site/content/docs/5.0/content/typography.md
- site/content/docs/5.0/guidelines/navigation.md
Closes #520 
---
- Firefox ESR
- iOS Safari
---
**Preview**: https://deploy-preview-595--boosted.netlify.app/docs/5.0/content/typography/#links
> Links with chevron

- scss/_dropdown.scss
- scss/_variables.scss
- scss/boosted-grid.scss
- scss/boosted-reboot.scss
- scss/boosted-utilities.scss
- scss/boosted.scss
- site/data/docs-versions.yml
- site/layouts/partials/docs-versions.html
Also onboards a fix for dropdowns.
> Docs/mention v4.6

- .github/workflows/browserstack.yml
- .github/workflows/bundlewatch.yml
- .github/workflows/css.yml
- .github/workflows/dart-sass.yml
- .github/workflows/docs.yml
- .github/workflows/js.yml
- .github/workflows/lint.yml
- scss/_alert.scss
- scss/_close.scss
- scss/_modal.scss
- scss/_toasts.scss
- scss/_variables.scss
- site/content/docs/4.6/components/modal.md
Closes #606 
Only missing "Modal with image" since it's a new feature.
---
First draft:
- Firefox ESR
- iOS Safari
---
Preview: https://deploy-preview-615--boosted.netlify.app/docs/4.6/components/modal/#examples
> Branded modals (backport #611)

- .bundlewatch.config.json
- scss/_badge.scss
- scss/_variables.scss
- scss/utilities/_background.scss
- site/content/docs/4.6/utilities/colors.md
Closes #610 
---
- Badges preview: https://deploy-preview-619--boosted.netlify.app/docs/4.6/components/badge/#contextual-variations
- Utilities preview: https://deploy-preview-619--boosted.netlify.app/docs/4.6/utilities/colors/#background-color
> Branded badges and backgrounds

- scss/orangeIcons.scss
> Accessibility icon

- js/src/dropdown.js
Close #643 
---
Also that was a Boosted mod: another `diff` in the wall :heart: 
---
Preview: https://deploy-preview-646--boosted.netlify.app/docs/4.6/components/dropdowns/
> Stop focusing the first item when opening

- .github/workflows/pa11y.yml
add a step to update sri otherwise pa11y-ci failed to load css and js in case of update
> fix(action): update sri before running local documentation for pa11y

- README.md
- site/content/docs/5.0/migration.md
> fix(#694): replace the boosted.netlify doc links with /docs/5.0

- site/content/docs/5.0/components/toasts.md
changed toast color within Live section from blue to orange
> Toast color fix

- scss/_o-navbar.scss
> Fix orange navbar 1px border bottom color

- scss/_navbar.scss
- site/content/docs/5.1/components/navbar.md
- site/content/docs/5.1/examples/cheatsheet-rtl/index.html
- site/content/docs/5.1/examples/cheatsheet/index.html
- site/content/docs/5.1/examples/navbars/index.html
* Remove .navbar-light examples not valid by design
* Fix "Boosted mod" comments
* [Fix "Navbar > Supported content" description](https://deploy-preview-885--boosted.netlify.app/docs/5.1/components/navbar/#supported-content)
> Minor fixes around Navbar component

- site/content/docs/4.6/components/pagination.md
- site/content/docs/4.6/examples/news-template/index.html
> Missing `.has-label` in some `.page-item` list elements

- site/layouts/_default/docs.html
- site/layouts/_default/guidelines.html
> fix(#902): change page title padding top on md screens

- scss/_variables.scss
- site/content/docs/4.6/utilities/embed.md
Closes #909 
**Preview**: https://deploy-preview-908--boosted.netlify.app/docs/4.6/utilities/embed/
> V4 dev mewenleho portrait videos

- site/content/docs/5.1/customize/optimize.md
**Preview**: https://deploy-preview-985--boosted.netlify.app/docs/5.1/customize/optimize/#unused-css
> Fix broken links in 'Unused CSS' section

- site/content/docs/5.1/components/offcanvas.md
**Preview**: https://deploy-preview-986--boosted.netlify.app/docs/5.1/components/offcanvas/#offcanvas-components
> Docs: Replace Bootstrap reference with Boosted in Offcanvas example

- site/layouts/partials/docs-navbar.html
Ensure that hovering "Download" button of the header doesn't display it with a black bg on a black bg header.
> Docs: use `.btn-inverse` for download button in main header

- scss/_o-step-bar.scss
- scss/_variables.scss
- site/content/docs/4.6/components/stepbar.md
Backport to v4 the design of Stepbars. (38px height to 30px)
Preview : [link](https://deploy-preview-1039--boosted.netlify.app/docs/4.6/components/stepbar/)
> Orange stepbar

- scss/_navbar.scss
- scss/_orange-navbar.scss
- scss/_variables.scss
- site/content/docs/5.1/examples/navbar-sticky/index.html
- site/content/docs/5.1/examples/navbar-sticky/navbar-sticky.css
- site/data/examples.yml
- site/layouts/shortcodes/orange-global-headers.html
- site/layouts/shortcodes/orange-supra.html
Signed-off-by: Isabelle Chanclou <isabelle.chanclou@orange.com>
> Sticky header example

- package-lock.json
- package.json
* ~~https://github.com/AmauriC/tarteaucitron.js/commit/bc99c2d53a312c86581aa344c44f6e437c69f8a0~~
* ~~https://github.com/AmauriC/tarteaucitron.js/commit/cfee13904c9a703dd711697ac726aea1dfbc2c70~~
* ~~https://github.com/AmauriC/tarteaucitron.js/commit/83800099749be6dd888365c6fb9e73809d84f891~~
* ~~https://github.com/AmauriC/tarteaucitron.js/commit/70dcf7656c513f7adeba00d5b2b909188eb64b7e~~
* ~~https://github.com/AmauriC/tarteaucitron.js/commit/acd12e32028b556ca42cb512ec25e33f7ec666e6~~
* ~~https://github.com/AmauriC/tarteaucitron.js/commit/259102b4f18e487307887598eb0ded7b62263997~~
* ~~https://github.com/AmauriC/tarteaucitron.js/commit/5e42fdeb3fae80561857f261c4503f8f74287791~~
* ~~https://github.com/AmauriC/tarteaucitron.js/commit/346a251cf0f12294adec445934486a5db9596bb5~~
* …
> chore(dependencies): bump tarteaucitronjs from 1.9.5 to 1.9.6

- site/content/docs/5.1/customize/color.md
> fix(color): add indigo to colors (existing but not documented).

- site/assets/scss/_boosted.scss
- site/assets/scss/_footer.scss
> Clever sticky footer

- scss/_pagination.scss
- scss/_variables.scss
Also remove margin at start
Backport of #1120 to v4
> fix(pagination): Remove space between pagination numbers in v4

- scss/_reboot.scss
Fixes #1156 
Backport the v5 changes done in #1248.
> Patching list color v4

- scss/_back-to-top.scss
- scss/_variables.scss
For a better alignment: 
- pull up icon of 1px
- pull up label of 1px
Closes #1173
> fix(back-to-top): icon and label positioning

- scss/_variables.scss
- scss/forms/_form-check.scss
- site/assets/js/snippets.js
- site/content/docs/5.2/forms/checks-radios.md
Closes #1318 
* indeterminate:
* disabled:
> Checkbox fixes

- scss/_o-footer.scss
- site/content/docs/4.6/components/orange-footer.md
- site/content/docs/4.6/examples/news-template/index.html
- site/content/docs/4.6/examples/orange-form/index.html
- site/content/docs/4.6/examples/orange-homepage/index.html
- site/layouts/partials/boostwatch/ofooter.html
Fixes #655 
Refresh the examples pages since it wasn't aligned anymore due to my changes
> Footer focus change

- scss/_variables.scss
- scss/mixins/_forms.scss
Fixes #1358 
Bs only change the background-image so we do the same.
> Fix the background color for validated input

- js/tests/unit/dom/event-handler.spec.js
Small one with https://github.com/twbs/bootstrap/commit/f451b4161e4e499f5d1b743802302e6b19a5dc4c but that will allow to re-enable one test that was disabled in a previous Bootstrap > Boosted merge.
> Chore merge/main@f451b41

- site/assets/scss/_component-examples.scss
- site/content/docs/4.6/utilities/borders.md
> Border utility: make subtractive borders 2px

- scss/_forms.scss
- scss/_variables.scss
- site/content/docs/4.6/components/forms.md
Minor aside fix: feedback looks more related to its input.
Is there anything to write inside the migration guide ?
> `.form-text`: fix margin-top, font-size and color

- site/content/docs/5.2/content/reboot.md
Introduce a third level list item to show how it is displayed in Boosted.
> Docs: third level Reboot list 

- scss/_list-group.scss
- scss/_variables.scss
- site/content/docs/5.2/components/list-group.md
First round of dark variant for list-group.
> List-group: Add dark variant

- site/assets/scss/_footer.scss
Fixes #1592 
Restore class bd-footer in scss : 
- add attributes to make footer stick to bottom on small pages (position: sticky and top: 100vh)
- add Boosted mod because I don't get back Boosted css for links in footer (not accurate)
Makes footer stick to bottom on small pages again, but still bottom for big pages (at it was before PR #1280)
* https://deploy-preview-1596--boosted.netlify.app/docs/5.2/guidelines/
> Footer: make footer stick to bottom on small pages

- scss/mixins/_background-variant.scss
> Links: fix hover state on dark background

- .cspell.json
- site/content/docs/5.2/components/orange-navbar.md
- site/layouts/shortcodes/orange-global-headers.html
- site/layouts/shortcodes/orange-supra.html
> fix(docs): typo in Spanish

- site/content/docs/5.2/examples/cards-rtl/index.html
- site/content/docs/5.2/examples/cards/index.html
- site/content/docs/5.2/examples/footers/index.html
- site/content/docs/5.2/examples/grid/index.html
- site/content/docs/5.2/examples/masonry/index.html
- site/content/docs/5.2/examples/navbar-sticky/index.html
- site/content/docs/5.2/examples/navbars/index.html
- site/content/docs/5.2/examples/stickers/index.html
- site/content/docs/5.2/examples/tags/index.html
- site/content/docs/5.2/examples/title-bars/index.html
This PR adds aliases for all `index.html`s used for our examples.
It fixes latest URLs for all our examples; e.g.:
* boosted.orange.com/docs/examples/footers
* boosted.orange.com/examples/footers
* https://deploy-preview-1657--boosted.netlify.app/docs/5.2/examples/footers/
* https://deploy-preview-1657--boosted.netlify.app/docs/examples/footers/
* https://deploy-preview-1657--boosted.netlify.app/examples/footers/
* https://deploy-preview-1657--boosted.netlify.app/docs/5.2/examples/cards/
* https://deploy-preview-1657--boosted.netlify.app/docs/examples/cards/
* https://deploy-preview-1657--boosted.netlify.app/examples/cards/
* https://deploy-preview-1657--boosted.netlify.app/docs/5.2/examples/stickers/
* …
> fix(docs): add aliases for examples

- .bundlewatch.config.json
- js/src/tooltip.js
- scss/_carousel.scss
- scss/_functions.scss
- scss/boosted-utilities.scss
- site/content/docs/5.2/migration.md
Bootstrap v5.2.3 is only composed of 4 commits that were cherry-picked from their _main_ branch:
* https://github.com/twbs/bootstrap/commit/2b21094074b1bdabf9ebc4095c29398f8b2de237
* https://github.com/twbs/bootstrap/commit/60b02041c4a4bffcd1ec5ccee78126c10732cae2
* https://github.com/twbs/bootstrap/commit/5029370a10717892192d60b88c0406bdd9450fc2
* https://github.com/twbs/bootstrap/commit/01dc2f51003947408b1237fd4c58c0f078596378
This PR gathers those modifications directly in our _main_ branch in order to release a future v5.2.3 for Boosted.
Note: I've added a commit to begin our migration guide section for the v5.2.3.
> chore(merge): cherry-picked commits in Bootstrap v5.2.3

- site/layouts/partials/docs-versions.html
Remove link to 404.
* https://deploy-preview-1692--boosted.netlify.app/
> Remove 404 link in previous releases menu

- site/content/docs/5.3/migration.md
Remove unnecessary  `.text-danger-emphasis` class.
Keep the migration guide consistent.
https://deploy-preview-1905--boosted.netlify.app/docs/5.3/migration/#components
- (NA) My change follows accessibility good practices; I have at least run axe
- (NA) My change respects the design guidelines defined in [Orange Design System](https://system.design.orange.com/0c1af118d/p/8118d1-web)
- (NA) My change is compatible with responsive display
- (NA) My change follows the [developer guide](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/wiki/Developer-guide)
- (NA) My change introduces changes to the documentation and/or …
> Remove unnecessary class for better consistency of the migration guide

- .cspell.json
- build/vnu-jar.js
- site/assets/scss/_content.scss
- site/content/docs/5.3/examples/_index.md
- site/content/docs/5.3/getting-started/javascript.md
- site/content/docs/5.3/getting-started/parcel.md
- site/content/docs/5.3/getting-started/vite.md
- site/content/docs/5.3/getting-started/webpack.md
- site/data/examples.yml
- site/layouts/shortcodes/scss-docs.html
> Chore merge from 99867eb to f8a56da

- README.md
This PR removes the Orange logo from our README.
Action required by the Brand team.
> Docs: remove Orange logo from README

- package-lock.json
- package.json
> Merge from 3374ea5 to 032f2b1

- .github/workflows/update-pr-desc-links.yml
This PR adds a workflow to automatically update Netlify preview URLs after opening a PR.
> chore(workflows): add a workflow to automatically update Netlify preview URLs after opening a PR

- package-lock.json
- package.json
> chore(merge main): patched commit → 08cde8d

- package-lock.json
- package.json
- ~https://github.com/twbs/bootstrap/commit/b7ce0b696176817c923b6dfd0e0253d2442fab6d~: already merged via Dependabot
> Merge Bootstrap commits from b7ce0b6 to de6b9a7

- site/content/docs/5.3/examples/stickers/index.html
NA
Set the correct id on stickers svg
NA
- <https://deploy-preview-2066--boosted.netlify.app/docs/examples/stickers>
- (NA) My change introduces changes to the documentation and/or I have updated the documentation accordingly
- (NA) My new component is added in Storybook
> Stickers example: fix id

- site/content/docs/5.3/migration.md
In migration guide:
- remove newline in Alert component
- move Footer section at the right place
Fix some small issues in migration guide apart from any other changes
- <https://deploy-preview-2074--boosted.netlify.app/>
- (NA) My change introduces changes to the documentation and/or I have updated the documentation accordingly
- (NA) My new component is added in Storybook
- (NA) Manually run [BrowserStack tests](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/actions/workflows/browserstack.yml)
- (NA) Manually test browser compatibility with BrowserStack (Chrome >= 60, Firefox >= 60 (+ …
> Fix small issues on migration guide

- site/content/docs/5.3/components/progress.md
- site/data/design-guidelines.yml
This PR fixes some broken DSM links.
- <https://deploy-preview-2126--boosted.netlify.app/>
> fix(docs): update broken DSM links

- site/assets/scss/_sidebar.scss
- site/assets/scss/_variables.scss
- site/layouts/partials/docs-navbar.html
NA
Add new banner with `d-none` to ease new version link.
Ease process
- <https://deploy-preview-2150--boosted.netlify.app/docs>
> Banner for newer version of Boosted

- scss/_variables.scss
NA
Add our missing prefix. Revert part of #573.
Bug concerning the custom interval that can be set on carousel indicators.
- https://deploy-preview-2203--boosted.netlify.app/docs/5.3/components/carousel/#individual-carousel-item-interval
- (NA) My change introduces changes to the documentation and/or I have updated the documentation accordingly
> Carousel: Fix for custom carousel item interval

- .github/workflows/update-pr-review-in-progress.yml
NA
Change the review trigger to `changes_requested` only.
Comments on pull requests change the column of the associated card in the board. It was a bit annoying.
> Workflow: fix issue on comment

- .github/workflows/update-pr-approved.yml
NA
Add some conditions to get the right column to move.
If the labels `ready for *` were already placed on the PR for any reason, the card moved on the `Need Lead Dev Review` directly.
> Workflow: fix approved workflow by adding conditions

- site/content/docs/5.3/dark-mode.md
- Breaking change (fix or feature that would change existing functionality)
- <https://deploy-preview-2272--boosted.netlify.app/>
> Add stepped process and local nav examples

- package-lock.json
- package.json
- scss/forms/_form-check.scss
- site/content/docs/5.3/helpers/stacks.md
> Merge from 9e5e22a to 4dd9bf0

- package-lock.json
- package.json
- site/assets/scss/_component-examples.scss
- site/content/docs/5.3/components/popovers.md
> Merge from 323f9d6 to 72d6722

- .github/workflows/update-pr-approved.yml
- .github/workflows/update-pr-design-a11y-approved.yml
- .github/workflows/update-pr-ready-review.yml
- .github/workflows/update-pr-review-in-progress.yml
NA
Increase limit number of cards inside a project.
Working on small PRs make the limit overpass quite fast. 
- NA
- NA I have added JavaScript unit tests to cover my changes
- NA I have added SCSS unit tests to cover my changes
- NA My change introduces changes to the documentation and/or I have updated the documentation accordingly
- NA My change introduces changes to the migration guide
- NA My new component is well displayed in [Storybook](https://deploy-preview-2312--boosted.netlify.app/storybook)
- NA My new component is compatible with RTL
- NA Manually run [BrowserStack tests](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/act …
> Workflows: Increase limit number of cards

- scss/_variables.scss
- site/content/docs/5.3/dark-mode.md
Modals in dark mode, by using existing Sass vars :
| `$modal-content-color` | `null` | `var(--#{$prefix}body-color)` |
⚠️ Need a `data-bs-theme="body"` somehow ?
- https://deploy-preview-2322--boosted.netlify.app/docs/5.3/components/modal
- https://deploy-preview-2322--boosted.netlify.app/docs/5.3/dark-mode/#modal
> Dark mode: Modal

- site/assets/js/tac.js
- site/assets/scss/_tarteaucitron.scss
Tarteaucitron modal and banner in dark mode.
- https://deploy-preview-2339--boosted.netlify.app/
> Dark mode: Tarteaucitron

- scss/_back-to-top.scss
- scss/_variables.scss
- site/content/docs/5.3/dark-mode.md
Back to top in dark mode, by using existing and new Sass vars :
| `$back-to-top-title-color` | - | `var(--#{$prefix}body-color)` |
| `$back-to-top-title-bg-color` | `$white` | `var(--#{$prefix}body-bg)` |
| `$back-to-top-bg` | - | `var(--#{$prefix}highlight-color)` |
| `$back-to-top-icon-margin-left` | - | `$spacer * .5` |
- https://deploy-preview-2329--boosted.netlify.app/docs/5.3/components/back-to-top
- https://deploy-preview-2329--boosted.netlify.app/docs/5.3/dark-mode/#back-to-top
> Dark mode: Back to top

- scss/_variables.scss
- site/content/docs/5.3/dark-mode.md
Offcanvas in dark mode, by using existing Sass vars :
| `$offcanvas-bg-color` | `var(--#{$prefix}body-bg)` | `$modal-content-bg` |
| `$offcanvas-bg-color` | `null` | `$modal-content-color` |
⚠️ Need a `data-bs-theme="body"` somehow ?
- https://deploy-preview-2348--boosted.netlify.app/docs/5.3/components/modal
- https://deploy-preview-2348--boosted.netlify.app/docs/5.3/dark-mode/#modal
> Dark mode: Offcanvas

- package-lock.json
- package.json
- site/content/docs/5.3/components/offcanvas.md
- site/content/docs/5.3/examples/download-app/download-app.css
- site/static/docs/5.3/assets/js/color-modes.js
> Chore: merge from d769ae0 to a4d2f59

- site/content/docs/5.3/dark-mode.md
Tooltips in dark mode
- https://deploy-preview-2352--boosted.netlify.app/docs/5.3/components/tooltips
- https://deploy-preview-2352--boosted.netlify.app/docs/5.3/dark-mode/#tooltips
> Dark mode: Tooltips

- js/tests/visual/scrollspy.html
- scss/_navbar.scss
- scss/_variables.scss
- site/assets/scss/_subnav.scss
- site/content/docs/5.3/components/navbar.md
- site/content/docs/5.3/components/orange-navbar.md
- site/content/docs/5.3/dark-mode.md
- site/content/docs/5.3/examples/download-app/index.html
- site/content/docs/5.3/examples/form/index.html
- site/content/docs/5.3/examples/navbar-sticky/index.html
- site/content/docs/5.3/examples/navbars/index.html
- site/layouts/partials/docs-navbar.html
- site/layouts/shortcodes/orange-global-headers.html
- site/layouts/shortcodes/orange-supra.html
- Need to check the main global header of the documentation
- ~~Fixed a bug in main branch happening since we changed the behavior of minimized navbar. We can remove 3lines if we want to make it happen to main directly.~~
Navbars in dark mode, by using existing Sass vars :
| `--#{$prefix}navbar-bg` | - | `$navbar-light-bg` |
| `--#{$prefix}navbar-toggler-icon-filter` | `none` | - |
| `--#{$prefix}navbar-toggler-icon-color` | - | `$navbar-light-icon-color` |
| `--#{$prefix}navbar-toggler-icon-hover-color` | - | `$navbar-light-icon-hover-color` |
| `$navbar-light-bg` | - | `var(--#{$prefix}highlight-color)` |
| `$navbar-light-hover-color` | `$accessible-orange` | `var(--#{$prefix}link-hover-color)` |
| …
> Dark mode: Navbar & Orange navbar

- site/layouts/partials/home/masthead.html
NA
Adding a link to the latest migration guide.
Better visibility of the new version.
- <https://deploy-preview-2366--boosted.netlify.app/>
> Docs: Adding a link on the homepage

- scss/_variables.scss
- site/content/docs/5.3/examples/masonry/index.html
⚠️ Might be merged once `data-bs-theme="inverted"` is introduced.
- https://deploy-preview-2369--boosted.netlify.app/docs/5.3/examples/masonry
> Add color mode on Masonry example

- site/content/docs/5.3/examples/grid/grid.css
- site/content/docs/5.3/examples/grid/index.html
- https://deploy-preview-2368--boosted.netlify.app/docs/5.3/examples/grid
> Dark mode: Grid example

- site/assets/scss/_content.scss
- site/layouts/partials/home/components-utilities.html
Proposals to get closer to Bootstrap. One of them should happen anyway in dark mode branch.
- https://deploy-preview-2374--boosted.netlify.app/
> Docs: Homepage tweaks

- site/assets/scss/_navbar.scss
- site/layouts/_default/single.html
- site/layouts/partials/home/masthead.html
Remove some useless CSS due to our new implementation of dropdowns.
Make sure the docs header works as expected.
- https://deploy-preview-2377--boosted.netlify.app/
> Remove useless CSS since dropdown have been changed

- site/content/docs/5.3/dark-mode.md
This PR adds the placeholder component in the `/dark-mode` page as a sub-task listed in https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/2223.
- https://deploy-preview-2391--boosted.netlify.app/docs/5.3/dark-mode/#placeholders
> Dark mode: Placeholders

- scss/_variables.scss
This PR fixes the pagination item hover background.
- https://deploy-preview-2405--boosted.netlify.app/docs/5.3/dark-mode/#pagination
> Dark mode: Pagination fix

- site/layouts/partials/docs-navbar.html
This PR tackles the following sub-task of https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/1776:
> When the right commit will be added to Boosted from Bootstrap, don't forget to remove this modification: https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/commit/a624a5d73f0e2c580a3daeea3f61e7d3c9e07978
- <https://deploy-preview-2423--boosted.netlify.app/>
> Dark mode: toggle theme

- site/content/docs/5.3/components/accordion.md
- site/content/docs/5.3/components/alerts.md
- site/content/docs/5.3/components/breadcrumb.md
- site/content/docs/5.3/components/buttons.md
- site/content/docs/5.3/components/close-button.md
- site/content/docs/5.3/components/list-group.md
- site/content/docs/5.3/components/local-navigation.md
- site/content/docs/5.3/components/pagination.md
- site/content/docs/5.3/components/stepped-process.md
- site/content/docs/5.3/components/tags.md
- site/content/docs/5.3/forms/checks-radios.md
- site/layouts/shortcodes/callout-deprecated-dark-variants.html
Handle the deprecation of dark variants with a shortcode directly.
- https://deploy-preview-2419--boosted.netlify.app/
> Dark mode: Handle properly dark variants

- scss/_accordion.scss
- scss/_carousel.scss
- scss/_dropdown.scss
- scss/_navbar.scss
- scss/_variables.scss
- scss/forms/_form-select.scss
- site/assets/scss/_navbar.scss
- site/assets/scss/_syntax.scss
Handle the deprecation of dark variants inside scss files.
- https://deploy-preview-2422--boosted.netlify.app/
> Dark mode: Deprecate variables and CSS classes

- scss/_dropdown.scss
- scss/_variables.scss
Following the desin updates for the dark mode.
Also remove the focus state of the active state that is no longer relevant.
- https://deploy-preview-2417--boosted.netlify.app/dark-mode/#dropdowns
- https://deploy-preview-2417--boosted.netlify.app/docs/components/dropdowns
> Dark mode: Dropdown fix design

- package-lock.json
- package.json
- scss/tests/mixins/_utilities.test.scss
- site/layouts/_default/examples.html
- site/layouts/partials/docs-navbar.html
> Chore merge from 240b78e to e47f3fe

- site/content/docs/5.3/components/alerts.md
- site/content/docs/5.3/components/list-group.md
- site/content/docs/5.3/migration.md
- site/layouts/partials/home/get-started.html
> Chore merge from ce1bf1c to 85b1d1c

- package-lock.json
- package.json
> Merge chore main from fa9c12a to 99562ba

- package-lock.json
- package.json
- site/layouts/_default/single.html
- site/layouts/partials/home/masthead.html
> Chore merge main from 712e722 to bf8f2d2

- package-lock.json
- package.json
> Chore merge main from ee3bf1b to f68a47c

- .eslintrc.json
- package-lock.json
- package.json
> Chore merge from 1a3c287 to 868705b

- package-lock.json
- package.json
> chore(merge main): patched commit → ad0cc68

- package-lock.json
- package.json
> chore(merge main): patched commit → d7b22b7

- package-lock.json
- package.json
- scss/_button-group.scss
- site/content/docs/5.3/components/button-group.md
- site/content/docs/5.3/getting-started/introduction.md
> chore(merge main): patched commit → 0932761

- .eslintrc.json
- package-lock.json
- package.json
> Chore merge main from 008bc23 to 7c39249

- .github/ISSUE_TEMPLATE/bug_report.yml
- .github/ISSUE_TEMPLATE/feature_request.yml
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/issue-labeled.yml
- README.md
- build/banner.mjs
- js/src/orange-navbar.js
- js/src/quantity-selector.js
- scss/mixins/_banner.scss
- site/assets/js/color.js
- site/assets/js/partials/back-to-top.js
This PR changes the blob reference from `/blob/main` to `/blob/ouds/main` to target the right OUDS main branch.
> [OUDS] Change blob reference from `/blob/main` to `/blob/ouds/main`

- .github/CONTRIBUTING.md
- .github/PULL_REQUEST_TEMPLATE.md
- .github/workflows/bundlewatch.yml
- .github/workflows/cspell.yml
- .github/workflows/css.yml
- .github/workflows/docs.yml
- .github/workflows/js.yml
- .github/workflows/lint.yml
- .github/workflows/node-sass.yml
- .github/workflows/pa11y.yml
- README.md
- nuget/ouds-web.sass.nuspec
- site/layouts/partials/footer.html
This PR hopes to be exhaustive 🙏 and modifies all remaining `main` branch occurrences in several files to switch to `ouds/main`.
> [OUDS] Switch `main` branch references to `ouds/main` branch

- README.md
- package-lock.json
- package.json
- site/content/docs/0.1/customize/sass.md
- site/content/docs/0.1/getting-started/download.md
- site/content/docs/0.1/getting-started/rtl.md
- site/layouts/partials/home/customize.html
- site/layouts/partials/home/get-started.html
- site/layouts/partials/home/masthead.html
This PR changes the npm package name from 'ouds-web' to '@ouds/web' (see https://www.npmjs.com/package/@ouds/web#ouds-web).
> [OUDS] Change npm package name from 'ouds-web' to '@ouds/web'

- package-lock.json
- package.json
- scss/_back-to-top.scss
- scss/_carousel.scss
- scss/_modal.scss
- scss/_navbar.scss
- scss/_reboot.scss
- scss/forms/_form-check.scss
- scss/forms/_quantity-selector.scss
I've compiled the `main` branch and this branch to compare them with `diff dist/css/boosted.css /tmp/boosted.main.css -U 5 > patch`.
We can see in the following diff that elements are moved but don't change the CSS rules applied to the selectors:
```diff
--- dist/css/boosted.css	2024-07-16 11:12:07
+++ /tmp/boosted.main.css	2024-07-16 11:11:40
@@ -255,18 +255,18 @@
}
:root {
scroll-padding-top: 3.75rem;
}
-@media (min-width: 1024px) {
+@media (prefers-reduced-motion: no-preference) {
:root {
-    scroll-padding-top: 7.5rem;
+    scroll-behavior: smooth;
}
}
-@media (prefers-reduced-motion: no-preference) {
+@media (min-width: 1024px) {
:root {
-    scroll-behavior: smooth;
+    scroll-padding-top: 7.5rem;
}
}
body {
position: relative;
\ No newline at end of file
@@ -3281,15 +3281,15 @@
} …
```
> Chore merge from e20cc0d to 7f8fed4

- js/src/dropdown.js
- js/src/tooltip.js
- js/src/util/index.js
- js/src/util/template-factory.js
- js/tests/unit/dropdown.spec.js
- js/tests/unit/popover.spec.js
- js/tests/unit/tooltip.spec.js
- js/tests/unit/util/index.spec.js
> Chore merge from 74891cb to 16cd80a4

- .github/CONTRIBUTING.md
- scss/_functions.scss
- scss/_variables.scss
- scss/mixins/_target-size.scss
- scss/mixins/_visually-hidden.scss
- site/content/docs/5.3/components/carousel.md
- site/content/docs/5.3/components/dropdowns.md
- site/content/docs/5.3/components/tooltips.md
- site/content/docs/5.3/getting-started/accessibility.md
- site/content/docs/5.3/migration.md
- site/content/docs/5.3/utilities/colors.md
> Chore merge from 4e954ea to 3083596

- package-lock.json
- package.json
> chore(merge main): patched commit → e3e00b5

- package-lock.json
- package.json
> chore(merge main): patched Boosted commit → e42878f

- scss/_variables.scss
NA
Fix typo that appear on our documentation.
Typo fix
- <https://deploy-preview-2718--boosted.netlify.app/docs/helpers/ratio>
> Docs: Fix typo in Scss file

- package-lock.json
- package.json
- site/content/docs/5.3/about/overview.md
> chore(merge main): patched commit → 329acbd

- package-lock.json
- package.json
- site/content/docs/5.3/customize/options.md
> chore(merge main): patched commit → dce1df

- site/content/docs/5.3/components/modal.md
- site/content/docs/5.3/components/tooltips.md
> chore(merge main): patched commit → a7a45b2

- package-lock.json
- package.json
Supersedes #2796.
Removes eslint-plugin-storybook dependency since we have only auto-generated stories.
> chore(deps-dev): remove eslint-plugin-storybook dependency

- package-lock.json
- package.json
NA
Revert partially https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/commit/09bcdefc71ed722cfd8a5f0629b506c2c06e7b17, remove useless `@chromatic-com/storybook` dependency.
Remove useless dependency.
> chore(deps-dev): revert partially 09bcdef, remove useless `@chromatic-com/storybook` dependency

- site/content/docs/0.0/content/typography.md
- site/content/docs/0.0/getting-started/accessibility.md
- site/content/docs/0.0/getting-started/contents.md
- site/content/docs/0.0/getting-started/introduction.md
- site/content/docs/0.0/helpers/ratio.md
- site/content/docs/0.0/layout/columns.md
- site/content/docs/0.0/utilities/api.md
NA
Remove comments where they aren't needed anymore.
Have a consistent documentation.
- <https://deploy-preview-2851--boosted.netlify.app/docs/getting-started/accessibility>
- <https://deploy-preview-2851--boosted.netlify.app/docs/getting-started/contents>
- <https://deploy-preview-2851--boosted.netlify.app/docs/getting-started/introduction>
- <https://deploy-preview-2851--boosted.netlify.app/docs/helpers/ratio>
- <https://deploy-preview-2851--boosted.netlify.app/docs/layout/columns>
- <https://deploy-preview-2851--boosted.netlify.app/docs/utilities/api>
> [OUDS] fix(docs): missing changes in the previous branches

- site/data/core-team.yml
Adding Maxime as a team member
Well I just arrived so 😄 
- chore
- <https://deploy-preview-2880--boosted.netlify.app/docs/0.1/about/team/>
- (NA) My change follows accessibility good practices; I have at least run axe
- (NA) My change respects the design guidelines defined in [Orange Design System](https://oran.ge/dsweb)
- (NA) My change is compatible with a responsive display
- (NA) My new component is well displayed in [Storybook](https://deploy-preview-2880--boosted.netlify.app/storybook)
- (NA) Manually run [BrowserStack …
> chore: add Maxime as a team member

- .browserslistrc
> chore(merge main):patched commit → b1e16bd

- .cspell.json
- .github/CONTRIBUTING.md
- README.md
- scss/_card.scss
- site/content/docs/5.3/components/card.md
- site/content/docs/5.3/components/offcanvas.md
- site/content/docs/5.3/components/placeholders.md
- site/content/docs/5.3/components/tooltips.md
- site/content/docs/5.3/content/reboot.md
- site/content/docs/5.3/customize/sass.md
- site/content/docs/5.3/getting-started/download.md
- site/content/docs/5.3/getting-started/parcel.md
- site/content/docs/5.3/getting-started/vite.md
- site/content/docs/5.3/getting-started/webpack.md
- site/data/translations.yml
> chore (merge main): patched commit → 99a0dc6

- site/content/docs/0.4/examples/dashboard/dashboard.css
- site/content/docs/0.4/examples/dashboard/dashboard.rtl.css
Add dashboard example generated css updates
Not commited in browserlist update
- <https://deploy-preview-3023--boosted.netlify.app/>
> [OUDS] fix generated css after browserlist update

- scss/_badge.scss
- site/src/content/docs/components/badge.mdx
Update badge size and examples
Take into account accessibility review
- <https://deploy-preview-3044--boosted.netlify.app/>
> [OUDS] Bagde updates following accessibility review

- scss/_variables.scss
- site/src/scss/docs.scss
closes #3036 
See Figma review
- <https://deploy-preview-3043--boosted.netlify.app/>
> [OUDS] fix: bullet list design review
