scss/_functions.scss

If you install `boosted: 4.0.0` as npm dependency, path `../node_modules/` in `scss/_functions.scss` do not exists in npm >= 3 environments.

fix node_modules path in `scss/_functions.scss`

---

scss/_o-nav.scss

fix(o-tab): update mediaquery size for switching from tab to accordions also on small view like tablet
Related to https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/131

o-tab - move tab to accordions on `sm` display

---

scss/_custom-forms.scss

Enabling the click on the orange background of a custom checkbox.

fix(custom-checkbox): remove unnecessary code #134

---

js/tests/unit/modal.js
js/tests/unit/scrollspy.js

following turned on zoom for DSF the scroll offsets can return fractional parts in chromium https://bugs.chromium.org/p/chromium/issues/detail?id=737777
There's a failed in unit tests

test(js): fix unit test for android mobile 

---

js/src/o-scroll-up.js
js/tests/unit/o-scroll-up.js
site/docs/4.3/components/scroll-up.md

add an option to scrollup component to allow passing an anchor to replace the top of the page
Usage : add `data-target="#myAnchor"` to the o-scroll-up component
Fixes #175

feat(scrollup): custom target

---

scss/_close.scss

Better way to remove transitionning `outline` on `:hover`.

fix(close): improve hover+focus styles for close button

---

scss/_custom-forms.scss

Apply solid outline with offset transition to custom range input as well.
Use primary color for range thumb on focus, aligning behaviour with the inactive state where thumb is the same color than track.

Obvious focus styles to fix #250

---

scss/_functions.scss
scss/vendor/_pow.scss

Somehow related to [Bootstrap #22996](https://github.com/twbs/bootstrap/pull/22996). ~~Maybe try another PR~~.

WCAG contrast algo

---

scss/_navbar.scss

In _navbar.scss, line 487, replace align-self: flex-end by align-self: flex-end
Fix #343

Fix dropdown menu alignment

---

NOTICE.txt
scss/orangeHelvetica.scss
scss/orangeIcons.scss
site/docs/4.5/assets/js/vendor/tarteaucitron.services.js
site/docs/4.5/getting-started/introduction.md
site/docs/4.5/getting-started/rtl.md

Possibly found some English typos.
I haven't changed the content of _orangeHelvetica.css.map_ nor _orangeHelvetica.min.css.map_ because I suppose they are generated automatically ; but I don't know exactly how to do that 😃

fix(docs): some English typos

---

_config.yml
site/_includes/footer.html
site/docs/4.5/about/boosted-license.md

put back bootstrap_current_version value
/!\ bootstrap rename master branch so all license header link refering to bootstrap master license file are invalid

fix some broken links

---

scss/_badge.scss

Fixes #463 
Preview: https://deploy-preview-466--boosted.netlify.app/docs/4.5/components/badge/#contextual-variations
FYI, since v5 uses `.bg-*` utilities for this, it already uses supporting colors for badges: https://v5-dev--boosted.netlify.app/docs/5.0/components/badge/#background-colors

Use supporting colors for badges

---

site/content/docs/5.0/forms/layout.md

docs(forms): drop useless text in horizontal form example

---

site/assets/js/tac.js

Either we don't link to our cookies page or we add content to our cookies page; but for now, giving users more info about GTM cookies seems more important than linking to our own content.

docs(analytics): drop read more link

---

build/vnu-jar.js
scss/_custom-forms.scss
scss/_variables.scss

Fixes #566 
Mostly improves `select` disabled state, and lower contrasts for disabled fields' labels :skull_and_crossbones:  — to match the UI Kit.

Orange branded disabled state

---

.browserslistrc
.bundlewatch.config.json
scss/_back-to-top.scss
scss/_carousel.scss
scss/_close.scss
scss/_navbar.scss
scss/_reboot.scss
scss/_root.scss
scss/_type.scss
scss/_variables.scss
scss/boosted.scss
scss/mixins/_forms.scss
site/assets/js/tac.js
site/assets/scss/_boosted.scss
site/assets/scss/_skippy.scss
site/assets/scss/_variables.scss
site/content/docs/5.0/components/back-to-top.md
site/content/docs/5.0/customize/css-variables.md
site/content/docs/5.0/examples/cheatsheet-rtl/index.html
site/content/docs/5.0/examples/cheatsheet/cheatsheet.js
site/content/docs/5.0/examples/cheatsheet/index.html
site/content/docs/5.0/guidelines/buttons.md
site/content/docs/5.0/utilities/position.md
site/data/sidebar.yml
site/layouts/_default/docs.html
site/layouts/_default/guidelines.html
site/layouts/partials/footer.html
site/layouts/partials/skippy.html

Closes #523 
---
There's also a good case to use `var()` and custom properties to lighten up a few things, starting at `$chevron-icon` occurrencies.
- Firefox ESR
- iOS Safari
---
**Preview**: https://deploy-preview-600--boosted.netlify.app/docs/5.0/components/back-to-top/

Back-to-top

---

.github/workflows/browserstack.yml
.github/workflows/bundlewatch.yml
.github/workflows/css.yml
.github/workflows/docs.yml
.github/workflows/js.yml
.github/workflows/lint.yml
.github/workflows/node-sass.yml
.github/workflows/pa11y.yml
.github/workflows/percy.yml

Reduce our ecological footprint, somehow?
- [Skip action when a specific label is added or removed](https://github.community/t/how-can-i-keep-github-event-pull-request-labels-up-to-date-when-re-trying-a-workflow/119386/2)
- [Skip actions when an existing label is set](https://github.community/t/skip-action-when-label-already-on-pr-vs-on-label-create-event/121037/2)
Targets:
The other ones already fit their target: either by filetype (e.g. compile, lint, test, optimize images) or event type (e.g. notify on published release). I guess we're able to add a few labels, such as `skip:percy`, `skip:browserstack`, etc. And `skip:ci` should cancel all workflows, I guess.

CI optimizations

---

scss/_back-to-top.scss
scss/_reboot.scss
scss/_variables.scss
site/assets/scss/_boosted.scss
site/assets/scss/_variables.scss
site/content/docs/5.0/customize/options.md
site/content/docs/5.0/getting-started/accessibility.md

Focus might be hidden behind fixed header: this is a first attempt to provide a simple and generic solution.

Improve focus accessibility when fixed header/footer overlaps

---

scss/_stepped-process.scss
scss/_variables.scss

| File                        | `feature/stepped-process` | current refactor |
| ------------------------ | ---------------------------------- | --------------------- |
| `boosted.css`        |                             26.54ko |             26.49ko |
| `boosted.min.css` |                             24.24ko |             24.19ko |
Small yet useful :p

Refactor stepped process

---

.bundlewatch.config.json
scss/_stepped-process.scss
scss/_variables.scss
scss/boosted.scss
site/content/docs/5.0/components/stepped-process.md
site/content/docs/5.0/examples/cheatsheet-rtl/index.html
site/content/docs/5.0/examples/cheatsheet/index.html
site/content/docs/5.0/guidelines/navigation.md
site/data/sidebar.yml

Stepbar is being ported into v5 as "stepped process" component.
Everything has been adapted according to this change
---
Closes #524 
---
- including the "Sass" part using `scss-docs` shortcode
- in Design Guidelines probably
- in Cheatsheet / Cheatsheet RTL examples
- Firefox ESR
- iOS Safari
- in Ship List 
- in Migration Guide (if `back-from-v4`): renamed variables, changes in markup requirement,  etc.
---
- Preview: https://deploy-preview-636--boosted.netlify.app/docs/5.0/components/stepped-process/
- X-ref v4: https://boosted.orange.com/docs/4.6/components/stepbar/

feat: Stepped Process: add the component from v4

---

site/content/docs/5.0/components/button-group.md
site/content/docs/5.0/components/dropdowns.md
site/content/docs/5.0/components/navbar.md
site/content/docs/5.0/examples/album-rtl/index.html
site/content/docs/5.0/examples/album/index.html
site/content/docs/5.0/examples/blog-rtl/index.html
site/content/docs/5.0/examples/blog/index.html
site/content/docs/5.0/examples/carousel-rtl/index.html
site/content/docs/5.0/examples/carousel/index.html
site/content/docs/5.0/examples/cheatsheet-rtl/index.html
site/content/docs/5.0/examples/cheatsheet/index.html
site/content/docs/5.0/examples/dashboard-rtl/index.html
site/content/docs/5.0/examples/dashboard/index.html
site/content/docs/5.0/examples/navbar-fixed/index.html
site/content/docs/5.0/examples/navbar-static/index.html
site/content/docs/5.0/examples/offcanvas/index.html
site/content/docs/5.0/examples/pricing/index.html
site/content/docs/5.0/examples/product/index.html
site/content/docs/5.0/examples/starter-template/index.html
site/content/docs/5.0/examples/sticky-footer-navbar/index.html
site/content/docs/5.0/forms/checks-radios.md
site/content/docs/5.0/guidelines/buttons.md

Closes #642 
---
- dropped `.btn-outline-*` missed occurrences
- use split buttons instead of dropdowns in buttons-group docs for visual consistency
- add `role="group"` on `.btn-group` (to partially reverse to Bootstrap)
---
Preview: https://deploy-preview-645--boosted.netlify.app/docs/5.0/components/button-group/

Various docs improvements around buttons / buttons grou

---

site/content/docs/4.6/components/alerts.md
site/content/docs/4.6/components/breadcrumb.md
site/content/docs/4.6/components/pagination.md
site/content/docs/4.6/layout/grid.md

In some parts of the 4.6 documentation, we can see the following string `[comment]: #Boosted mod ` that shouldn't be there. This PR transforms those strings into comments as seen in other markdown files in the project.
Example: https://boosted.orange.com/docs/4.6/components/alerts/#additional-content

fix(docs): some '[comment]: boosted mod' appear in the documentation

---

site/assets/js/tac.js

closes #677 
This PR is a first step (minimalist modification/quick fix) improving the cookie consent panel rendering to close #677.
Is it enough or do we develop something more complex by using `modal-*` classes or something else?
Screenshot:
Note: buttons hover is a bit buggy, need to work on this.

fix(#677): improve cookie consent panel rendering

---

site/content/docs/5.0/getting-started/rtl.md
site/layouts/_default/docs.html

- In https://boosted.orange.com/docs/5.0/about/overview/ for example, the 'View on GitHub' link goes to https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/site/content/docs/5.0/about/overview.md (`main` branch) instead of https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/v5-dev/site/content/docs/5.0/about/overview.md (`v5-dev` branch)
- Add a missing character (`>`) in RTL starter template

2 fixes in v5 documentation

---

site/content/docs/5.0/about/overview.md

closes #688 
I've only added the already shipped Orange custom components. I think it would be weird to have in the list components not yet available; even if we know that some of them will be there someday because they are in the v4.
But by doing that, we must not forget to add them here in the future; maybe write it somewhere in the DoD 🤷 
Direct link to see the modification: https://deploy-preview-689--boosted.netlify.app/docs/5.0/about/overview/#custom-components

Orange custom components in about/overview

---

site/content/docs/4.6/boosted-migration.md

fix(#690): some links were broken in 'Migrating to Boosted v4' page

---

scss/_card.scss
site/content/docs/4.6/components/collapse.md

add a padding to `.card-body` to keep content aligned with accordion title fix #656

fix accordions padding / margin inconsistency 

---

package-lock.json

https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/714 was merged containing unwanted modifications in the `package-lock.json`: all 5.0.1 packages were bumped to 5.0.2 (not only the Boosted one).
I've preferred to create a new PR with a new commit to identify the problem rather than reverting the merge. Indeed, the next steps had not been done already: creating the tag, etc.
I've added a precision into the [DoD for release](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/wiki/DoD-for-release) to avoid repeating the error in the future.

Fix release 5.0.2

---

config.yml
site/content/docs/5.0/getting-started/introduction.md
site/content/docs/5.0/getting-started/rtl.md

closes #735 
This is a draft to suggest a solution to this problem. Need some technical help to check if this is the good solution.
If this solution is validated, some further development is needed:
- ~~Verify that `npm run release-sri` modifies those new integrity values~~

fix(#735): separate local fonts from CDN in the starter template

---

site/content/docs/5.0/components/buttons.md

fix(#733): prevent a redirection to the main page after clicking on social buttons

Social button fixed

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/dependabot.yml

PR to avoid those emails/notifications
```
Dependabot tried to add @ffoodd as a reviewer to this PR, but received the following error from GitHub:
POST https://api.github.com/repos/Orange-OpenSource/Orange-Boosted-Bootstrap/pulls/755/requested_reviewers: 422 - Reviews may only be requested from collaborators. One or more of the users or teams you specified is not a collaborator of the Orange-OpenSource/Orange-Boosted-Bootstrap repository. // See: https://docs.github.com/rest/reference/pulls#request-reviewers-for-a-pull-request
```

fix: update references of ff00dd to Nurovek

---

site/layouts/partials/docs-versions.html

To avoid having 5.0.x instead of 5.1.x in the version selector
If you think it is the correct way of doing that, I could propose this fix to Bootstrap too

docs(version): automatically retrieve latest version in version selector

---

README.md

Update the links to the issue templates and replace the Creative Commons license internal link by an external link to creativecommons.org.

fix(doc): update broken links in README.md

---

nuget/boosted.nuspec
nuget/boosted.sass.nuspec

It is not needed to modify everytime the content of _nuget/*.nuspec_ files with the new version of Boosted since the `nuget/MyGet.ps1` script uses the Boosted version within `package.json`.
Also did some modifications after having compared those files to the ones in Bootstrap.
This needs to be backported to v4.

chore(release): resync nuget/*.nuspec files with Bootstrap

---

package-lock.json

Sometimes, Bootstrap regenerates their `package-lock.json` and we don't.
They told me how they do that:
```
$ git clean -dfx
$ rm -f package-lock.json
$ npm i
```
After that, I compared the results with https://github.com/twbs/bootstrap/blob/main/package-lock.json and most of it seems OK.
For some packages as `autoprefixer` or `tarteaucitronjs` (for example), I've relaunched `npm i <package>` to pin the dependency and avoid a big jump into new versions.
The main issue that I observed is that some packages are downgraded in Boosted `package-lock.json` and not in Bootstrap and I don't know why:
* (`linkinator` || `stylelint`) > `meow` > (`camelcase-keys`, `indent-string`, `minimist-options`)
Note: it will fix https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/818

chore(deps): regenerate package-lock.json

---

.github/workflows/notify.yml

See https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/762 from Dependabot

chore(deps): bump mattermost/action-mattermost-notify from 1.0.0 to 1.1.0

---

.github/CODEOWNERS
.github/dependabot.yml
site/data/core-team.yml

* Add new members of the core team 🎉 
* Changing assignee for Dependabot and others since I'm responsible of the backlog/maintenance for the moment. We will see in the next weeks/months how to distribute the actions according to the fields of competence of everyone 😃

Update Core Team members list and change automatic assignee

---

scss/_buttons.scss

Signed-off-by: Isabelle Chanclou <isabelle.chanclou@orange.com>
In Firefox, the button icon is situated 1px too high compared to the same in Chrome or design specifications.
It occurs only in the ::before container. Otherwise, the icon is of the exact same height of 20px.
I propose a go around solution (didn't found out an other one) that seems to solve the problem. Thanks for checking if it is acceptable or not.

Fix (button): vertical alignment of icons within buttons in Firefox (#773)

---

site/content/docs/5.1/components/navbar.md
site/content/docs/5.1/examples/carousel-rtl/index.html
site/content/docs/5.1/examples/carousel/index.html
site/content/docs/5.1/examples/cheatsheet-rtl/index.html
site/content/docs/5.1/examples/cheatsheet/index.html
site/content/docs/5.1/examples/headers/index.html
site/content/docs/5.1/examples/navbar-fixed/index.html
site/content/docs/5.1/examples/navbar-static/index.html
site/content/docs/5.1/examples/navbars/index.html
site/content/docs/5.1/examples/offcanvas-navbar/index.html
site/content/docs/5.1/examples/sticky-footer-navbar/index.html

@Aniort pointed out to @Nurovek in his WIP development of Global Headers a missing `role=search` as an attribute of the `<form>`s.
This PR is a proposal to apply this feedback all over Boosted documentation.
If this PR is merged, @ffoodd , do you think Bootstrap would be interested in such a modification?

chore(a11y): add missing role='search' and type='search' in navbar component and examples

---

scss/_variables.scss
site/assets/scss/_component-examples.scss
site/content/docs/5.1/helpers/ratio.md

Closes #907 
**Preview**: https://deploy-preview-906--boosted.netlify.app/docs/5.1/helpers/ratio/

feat(ratio); add ratio for portrait videos #775

---

build/.pa11yci.json

All recent PRs are red for the pa11y execution. This PR is a proposal to remove `wait`, `concurrency` and `timeout` values from the configuration. Seems to be better that way.

Remove concurrency, wait and timeout configurations in pa11y

---

site/layouts/_default/docs.html
site/layouts/_default/guidelines.html
site/layouts/partials/footer.html

Add a top margin to the doc footer to avoid this rendering when the side menu is non collapsed and we scroll:
New rendering:

Layouts: add a top margin to the doc footer

---

site/assets/scss/_alerts.scss
site/assets/scss/_component-examples.scss
site/assets/scss/docs.scss
site/content/docs/5.1/components/scrollspy.md
site/layouts/shortcodes/ods-incompatibility-alert.html

The 2 examples concerned in the issue shall be modified. In Bootstrap 5 and so far in Boosted 5, they are based on `navbar` (horizontal and vertical) component. As these cases don't exist in Orange Design system, here's a first proposal for replacing these 2 new examples based this time on `nav` component.
Preview: https://deploy-preview-923--boosted.netlify.app/docs/5.1/components/scrollspy/

Fix (scrollspy): Replace navbar and nested nav examples

---

config.yml
site/content/docs/5.1/getting-started/introduction.md

This section was present in [Boosted 4](https://boosted.orange.com/docs/4.6/getting-started/introduction/) and could be useful to reach Bootstrap developers or community.
**Preview**: https://deploy-preview-984--boosted.netlify.app/docs/5.1/getting-started/introduction/#bootstrap-community

Reintroduce Bootstrap Community section in introduction

---

.bundlewatch.config.json
scss/_button-group.scss
scss/_buttons.scss
scss/_dropdown.scss
site/content/docs/5.1/components/buttons.md
site/content/docs/5.1/components/dropdowns.md

This PR reintegrates `.btn-inverse` to handle buttons with dark background based on the `v4-dev` source code.
Note: for dropdowns, this PR only fixes the button and not the dropdown menu
**Live previews**:
* [Buttons](https://deploy-preview-1010--boosted.netlify.app/docs/5.1/components/buttons/) (non-regression)
* [Dark background buttons](https://deploy-preview-1010--boosted.netlify.app/docs/5.1/components/buttons/#dark-background)
* [Dropdowns](https://deploy-preview-1010--boosted.netlify.app/docs/5.1/components/dropdowns/) (non-regression)
* [Dark dropdowns](https://deploy-preview-1010--boosted.netlify.app/docs/5.1/components/dropdowns/#dark-dropdowns)
Closes #713 
Linked to #917

Buttons with dark background (`.btn-inverse`)

---

site/content/docs/4.6/components/toasts.md

This PR includes:
* https://github.com/twbs/bootstrap/commit/a3d14bb7b7814940229e972e606da2a7f397a237
* Refactoring:
* Add missing "Live" section
* Use only orange background
* Move the "Boosted mod" comments outside the area displayed in the documentation to avoid having it while copy/pasting the code

chore(merge-v4-dev): patched commit → a3d14bb

---

scss/_buttons.scss

Closes #1019
Icons in buttons icons should be 1px lower.

fix(#1019): modify buttons icons padding

---

site/content/docs/4.6/components/dropdowns.md

The example of split button in https://boosted.orange.com/docs/4.6/components/dropdowns/#split-button has "Secondary" as a label and "Action" in the corresponding source code.
1. It must be "Action"
2. They need to be coherent

Enhance split button doc example and fix button wording

---

scss/_variables.scss

Closes #1066 
Impact `$input-btn-line-height-lg` and so:
- `$btn-line-height-lg`
- `.btn-lg`: Large buttons — **Height has 2.5px in excess**
- `$input-line-height-lg` 
- `.input-group-lg` > *: Large form inputs — Not really visible
- `.col-form-label-lg`: Large form labels — Not really visible
- `.form-control-lg`: Large form controls — Not really visible
- `.blockquote-footer`: Quotes in cards — Minimal impact
- `$small-line-height`
- `.alert-sm`: Small alerts — Minimal impact
- `<small>` and `.small`: Depends on the use cases but should not be very visible
-  `$input-btn-line-height-sm`
- `$btn-line-height-sm`
- `.btn-sm`: **Small buttons  — Height has 1.5px in excess**
- `$input-line-height-sm`
- `.col-form-label-sm`: Small form labels — Minimal impact
- `.form-control-sm`: Small form …

FIX: Restore line heights var values by fixing `calc(divide())` operations

---

scss/_variables.scss
scss/forms/_form-check.scss

Closes #1072 
[Live Preview - Checks and radios](https://deploy-preview-1081--boosted.netlify.app/docs/5.1/forms/checks-radios/#switches)

fix(forms): vertically align labels for switches

---

site/layouts/partials/docs-navbar.html

Going onto [Orange Design System for web](https://deploy-preview-1083--boosted.netlify.app/docs/5.1/guidelines/) page make it active (and visible) in the menu bar.
If you do the same thing locally with the actual _main_ branch, the menu item won't be active.

fix(docs): make visible 'Design guidelines' menu item when the page is active

---

scss/forms/_form-check.scss

Closes #1074 
[Live Preview - Forms > Switches](https://deploy-preview-1082--boosted.netlify.app/docs/5.1/forms/checks-radios/#switches)

fix(forms): black outline for focused switches

---

scss/_dropdown.scss
scss/_variables.scss

Fix issue #657
Invert color of `.dropdown-menu`, and \.dropdown-menu-item` when hovered or active on `.bg-dark`  fix #657

fix dropdowns on `.bg-dark`

---

site/content/docs/5.1/components/alerts.md
site/content/docs/5.1/components/close-button.md

Alerts with dark background

---

scss/_variables.scss
site/content/docs/5.1/components/dropdowns.md
site/content/docs/5.1/customize/color.md

Changed the variables associated with dark-dropdowns + update the associated template
Dark components
Linked to #917.

Adjusting dark dropdowns

---

.bundlewatch.config.json
js/index.esm.js
js/index.umd.js
js/src/quantity-selector.js
js/tests/unit/quantity-selector.spec.js
scss/_forms.scss
scss/_variables.scss
scss/forms/_quantity-selector.scss
scss/mixins/_forms.scss
site/content/docs/5.1/about/overview.md
site/content/docs/5.1/customize/overview.md
site/content/docs/5.1/forms/overview.md
site/content/docs/5.1/forms/quantity-selector.md
site/content/docs/5.1/forms/validation.md
site/content/docs/5.1/getting-started/introduction.md
site/data/sidebar.yml

Closes #113 
Preview: https://deploy-preview-860--boosted.netlify.app/docs/5.1/forms/quantity-selector/
- including the "Sass" part using `scss-docs` shortcode
- in Cheatsheet / Cheatsheet RTL examples
- in /about/overview/#custom-components if it is a new Orange custom component
- in /gettings-started/introduction/#components if it is a new Orange custom component that requires JavaScript (and Popper)
- in /customize/overview#csps-and-embedded-svgs if it is a new Orange custom component that includes embedded SVGs in our CSS
- in /forms/validation/?#supported-elements if it is a new Orange custom component that is a form control
- Firefox ESR
- iOS Safari
- ~~Mention it in Migration Guide (if `back-from-v4`): renamed …

Quantity Selector

---

.bundlewatch.config.json
build/.pa11yci.json
scss/_nav.scss
scss/_variables.scss
site/content/docs/5.1/components/navs-tabs.md

Add in `Docs > Navs & tabs` the component `Tabs nested WEB-NAV-TAB-003` from https://system.design.orange.com/0c1af118d/p/44331c-navigation/b/9105e6/i/66611049![image](https://user-images.githubusercontent.com/89514509/148537270-0f01d0b7-b774-4049-97ae-2f572a2efb48.png)
Netlify link to look at what's done: 
https://deploy-preview-1017--boosted.netlify.app/docs/5.1/components/navs-tabs/#nested-tabs/

Docs(navs-tabs): add nested tabs

---

scss/_reboot.scss

doesn't only relies on polyfill focus-visible but also implement native :focus-visible
https://caniuse.com/css-focus-visible support is not so bad at time

implement default focus-visible

---

scss/_variables.scss
scss/forms/_form-check.scss
scss/forms/_labels.scss

This PR is a proposal to modify the margin left value between the required symbol (the `*`)  and the corresponding label.
The current value in Boosted is 6px: https://boosted.orange.com/docs/5.1/forms/overview/#required-field.
The value [defined in the DSM](https://system.design.orange.com/0c1af118d/p/88ab5b-forms/b/599459/i/48901789) is 3px.
[**Preview of the modification**](https://deploy-preview-1144--boosted.netlify.app/docs/5.1/forms/overview/#required-field) (@CyriaqueBillard I let you check the rendering and tell us if it sounds good to you)

fix(forms): change the margin left value between the required symbol and the label

---

scss/_buttons.scss

fix(social-btn): on dark background,need a white border so that the size of button doesn't decrease.
Closes #1121

fix(social-btn): add white border on dark background

---

site/content/docs/5.1/about/overview.md
site/content/docs/5.1/customize/overview.md
site/content/docs/5.1/getting-started/introduction.md

This PR is a proposal to reorder alphabetically the list of components in the documentation. IMHO it is simpler to find the components in the list and more natural.
**After the merge**

chore(docs): reorder alphabetically list of components

---

.bundlewatch.config.json
js/src/carousel.js
js/tests/unit/carousel.spec.js
scss/_carousel.scss
scss/_variables.scss
site/assets/scss/_component-examples.scss
site/content/docs/5.1/components/carousel.md

Closes [https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/1112](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/1112)

Provide a pause button for Carousels

---

config.yml

Before this modification, screen reader said "and ergonomic components library dot dot".
With this modification, screen reader will say ""and ergonomic components library".
/CC @Aniort ;) Thanks again for your presentation about screen readers. I tried it with Orca on Ubuntu.

fix(docs): replace '..' by '…' in the documentation title

---

scss/_utilities.scss
site/content/docs/5.1/utilities/text.md

Even if ODS forbids uppercase texts this utility can still be useful for some automatic rendering or depending on the context. I need it for example in https://deploy-preview-1214--boosted.netlify.app/docs/5.1/components/accordion/#example where `.text-uppercase` will display "html" → "HTML".

feat(utilities): reintroduce `.text-uppercase`

---

site/assets/scss/_tarteaucitron.scss

Fixes #1215 
This fix creates a `.tac_visually-hidden` rule from tarteaucitron.js by using `@include visually-hidden()` since we use the following configuration `useExternalCss: true`.
With `useExternalCss: false` we would have the content of `tarteaucitron.css` which contains a `.tac_visually-hidden` but this possibility hasn't been evaluated here.

fix(cookies): hide 'Cookies management panel' in the header

---

scss/_pagination.scss
scss/_variables.scss

and add new variable for margins at start and end (before and after numbers). 
Naming to see for this variable
I also had to correct line 107 to be able to commit (was sending an error), conforming to higher in the file.
closes #1120

fix(pagination): set margin between numbers to 0

---

site/content/docs/5.1/forms/checks-radios.md

Closes [#1127 ](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/1227)

fix(doc): add checks and radios without labels

---

.github/CODEOWNERS

Boosted Core Team prefers not have someone automatically set as reviewer. I chose to remove the content and not the file in order to remind us in the future the possibility to handle that differently.

chore(meta): remove CODEOWNERS content

---

scss/_sticker.scss
site/content/docs/5.1/components/sticker.md

Add CSS vars in Stickers component and Docs.
This is part of https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/1196.
Preview link: https://deploy-preview-1251--boosted.netlify.app/

feat(stickers): Add CSS vars for $sticker-

---

scss/_carousel.scss
scss/_variables.scss
site/content/docs/5.1/utilities/borders.md

Closes [#1084 ](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/1084)

Carousel navigation focus

---

site/assets/js/application.js

Fixes #1231 
The threshold I put here is nearly the smallest one, but maybe we can remove it from pages that are at least 2 times the viewport height ?

Remove back-to-top from small pages

---

package-lock.json

Fix the error observed in `v4-dev` PR by running `npm i swiper@6.5.1` to fix `package-lock.json`:
```
Run npm ci
npm ERR! code EUSAGE
npm ERR! 
npm ERR! `npm ci` can only install packages when your package.json and package-lock.json or npm-shrinkwrap.json are in sync. Please update your lock file with `npm install` before continuing.
npm ERR! 
npm ERR! Missing: svelte@3.48.0 from lock file
npm ERR! 
npm ERR! Clean install a project
npm ERR! 
npm ERR! Usage:
npm ERR! npm ci
npm ERR! 
npm ERR! Options:
npm ERR! [--no-audit] [--foreground-scripts] [--ignore-scripts]
npm ERR! [--script-shell <script-shell>]
npm ERR! 
npm ERR! aliases: clean-install, ic, install-clean, isntall-clean
npm ERR! 
npm ERR! Run "npm help ci" for more info
npm ERR! A complete log of this run can be found in:
npm ERR! …
```

fix(build): force swiper reinstall

---

scss/_buttons.scss

Fixes #1355 
Changing the active color of the button link to the one of the `:hover` state.

Fix active color of button link

---

site/assets/scss/_boosted.scss

Fixes #1353 
Use `scale()` instead of `scale:` due to [usability of scale](https://caniuse.com/mdn-css_properties_scale)

Fix boosted logo on homepage

---

site/layouts/_default/docs.html
site/layouts/_default/single.html
site/layouts/partials/ads.html

New margin (that can be compared to [the current one](https://boosted.netlify.app/docs/5.2/getting-started/introduction/))

chore(docs): small improvement to separate h1 and lead paragraph

---

scss/_back-to-top.scss

Fixes #1341
Please check all the weird edge cases you can think of and on different browsers/OS :)
Allowing actions under the transparent surface should be possible with this simple `pointer-events: none`.

Fix Back to top container to allow clicking under the transparent surface

---

site/assets/scss/_footer.scss
site/layouts/partials/footer.html

After an exchange with Cyriaque, we agreed to 
- Position the text to the right of the navigation links (so after these links).
- Delete the line break after the first sentence.
- Delete the list that surrounds the version number and the Netlify link.
Closes #1221

Use Footer component in docs

---

.github/workflows/browserstack.yml

Temporarily enable BrowserStack builds for each push to help BrowserStack support having several failed builds to analyze.

chore(workflows): temporarily enable BrowserStack for each push

---

package-lock.json
package.json

Linked to #1382
With tac > 1.8.4 (from 1.9.1) we got this error on Netlify:
```
09:43:12.735 Uncaught TypeError: document.getElementById(...) is null
color https://deploy-preview-1388--boosted.netlify.app/docs/5.2/assets/js/docs.min.js:6
color https://deploy-preview-1388--boosted.netlify.app/docs/5.2/assets/js/docs.min.js:6
addService https://deploy-preview-1388--boosted.netlify.app/docs/5.2/assets/js/docs.min.js:6
load https://deploy-preview-1388--boosted.netlify.app/docs/5.2/assets/js/docs.min.js:6
addScript https://deploy-preview-1388--boosted.netlify.app/docs/5.2/assets/js/docs.min.js:6
addInternalScript https://deploy-preview-1388--boosted.netlify.app/docs/5.2/assets/js/docs.min.js:6
load https://deploy-preview-1388--boosted.netlify.app/docs/5.2/assets/js/docs.min.js:6
onload …
```

chore(deps): revert tarteaucitronjs from 1.9.7 to 1.8.4

---

scss/_stepped-process.scss
scss/_variables.scss

Fix stepped process `line-height`

---

scss/_pagination.scss

Add CSS vars in Pagination component.

feat(pagination): Add CSS vars for $pagination

---

scss/_type.scss
scss/_variables.scss

The `.mark` padding of 0.2em used in Docs>About>Brand>#master-artwork and in Docs>Content>Typography>#inline-text-elements was vertically too much, occurring an overlapping on the text right above in a paragraph. To avoid that overlapping, the padding is removed on vertical axis in this PR.
**With the padding:**
**Without the paddding:**
Signed-off-by: Isabelle Chanclou <isabelle.chanclou@orange.com>

Delete .mark padding in Docs

---

scss/utilities/_text.scss
site/content/docs/4.6/utilities/text.md

Backport of #578. No need to backport on Bootstrap since they didn't support rtl.

Text break: remove for RTL and add a callout

---

scss/_variables.scss

Fixes #1483.
Reshape the arrow shape in order not to have a triangle but an arrow (avoid some limit cases issues such as zoom in page).

Stepped process: Fix arrow shape

---

scss/_variables.scss

Backport form v4.6: Fix of `<mark>` vertical padding to avoid overlapping on the lines above and below.  See #1465.
ℹ️  `<mark>` is no more used in Docs>About>Brand>#master-artwork, but only in Docs/content/typography/#inline-text-elements and in Example/cheatsheet not visible at the moment. In these pages, depending on the usage of the context, the change might not show.

Fix .mark padding (backport from v4.6)

---

site/content/docs/5.2/components/buttons.md

Set `Primary` instead of `Secondary` to be more consistent.

Docs: make buttons text descriptive of the used class

---

site/content/docs/5.2/components/accordion.md
site/content/docs/5.2/components/alerts.md

For consistency with Bootstrap docs architecture, I propose to move 'Dark variant' section out of the 'Example' section for alerts and accordions.
In Bootstrap:
- [Carousel > Dark variant](https://getbootstrap.com/docs/5.2/components/carousel/#dark-variant)
- [Close button > White variant](https://getbootstrap.com/docs/5.2/components/close-button/#white-variant)
- [Dropdowns > Dark dropdowns](https://getbootstrap.com/docs/5.2/components/dropdowns/#dark-dropdowns)
:pray: Please double-check if I haven't forgotten components in Boosted.

fix(docs): move 'Dark variant' sections out of 'Example' for alerts and accordions

---

package-lock.json

Update `package-lock.json` after modifications while running `npm i`. Probably not updated because of https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/commit/6278f08684ec17b33371da5545c81a63b394a7df.

chore(deps): update `package-lock.json`

---

.bundlewatch.config.json
scss/_breadcrumb.scss
scss/_pagination.scss
scss/_variables.scss
site/content/docs/5.2/components/breadcrumb.md

Not sure if this is the best solution but this is likely the smallest one since we define the color to inherit (cascading from `*-dark` rule) and background-color to transparent + active state of links are linked to `--#{$prefix}link-hover-color`. 
Related to #891.
Please check that [dark breadcrumbs](https://deploy-preview-1430--boosted.netlify.app/docs/5.2/components/breadcrumb/#dark-variant) are fine.

Breadcrumb: Add dark variant

---

scss/_back-to-top.scss
site/content/docs/5.2/components/back-to-top.md

Commits can be split if needed.
- Adding a missing CSS var on Back to top
- Removing the not branded variant.
Following the https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1428#issuecomment-1239036156.

Back to top: remove not branded variant

---

scss/_navbar.scss

Fixes #1523
`postcss-values-parser` returns a syntax error when a negative value is provided in a `calc` function after a CSS variable. We learnt that with https://github.com/twbs/bootstrap/commit/b8880e5eec6bb4f33578578ba2413f0d91424382 but we didn't know the issue could happen with divisions as well; at least we didn't think about it.
In order to review this PR, please execute the steps explained in the issue but instead of copying the code from the _main_ branch of the Boosted repository, please use the code provided in this branch.

fix(css): add workaround for postcss value parser error

---

.github/workflows/percy.yml
package-lock.json
package.json

Fixes #1527 
* Remove the use of the deprecated `percy/snapshot-action@v0.1.2`
* Used the [migration guide](https://github.com/percy/snapshot-action#deprecated) to rather use Percy CLI
This change is needed because `percy/snapshot-action@v0.1.2` is deprecated.
- Technical debt (workflows)
Go to [Percy](https://percy.io/) - Boosted dashboard
- ~~Check that `verbose: true` is still enabled~~

chore(workflows): replace percy/snapshot-action by Percy CLI

---

scss/_navbar.scss
scss/_variables.scss
site/content/docs/5.2/components/navbar.md

Set the default `border-color` to `#ccc` for more consistency and add some spacing to the form.

Docs: Navbar minor fixes

---

.bundlewatch.config.json
scss/_close.scss
scss/_variables.scss
site/content/docs/5.2/components/close-button.md

#1196.
Adding CSS var to close buttons.
Bootstrap probably won't do it on their side since they use filter for their variants. Moreover, we'll need them later to introduce more variants such as the outlined one.
New feature (non-breaking change which adds functionality)
* https://deploy-preview-1531--twbs-bootstrap.netlify.app/5.2/components/close
- including the "Sass" part using `scss-docs` shortcode
- in /about/overview/#custom-components if it is a new Orange custom component
- in /getting-started/introduction/#components if it is a new Orange custom component that requires JavaScript (and Popper)
- in /customize/overview#csps-and-embedded-svgs if it is a new Orange custom component that includes embedded SVGs in our CSS
- in /forms/validation/?#supported-elements if it is a new …

Close button: Adding CSS var

---

scss/mixins/_forms.scss

Fixes #1305 
This PR is a proposal to fix #1305 by:
* adding the same `padding-right` rule than in Bootstrap
* avoiding to display the valid icon for Quantity Selector (not enough space)
Dear reviewer please check all possible cases in forms when inputs are valid.
* [Forms > Validation > Custom styles](https://deploy-preview-1306--boosted.netlify.app/docs/5.1/forms/validation/#custom-styles)
* [Forms > Validation > Supported elements](https://deploy-preview-1306--boosted.netlify.app/docs/5.1/forms/validation/#supported-elements)

fix(forms): hide input control text under valid icon

---

scss/mixins/_utilities.scss

Issue reported by @Lausselloic with the following project: [demo-custom-build.zip](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/files/9838923/demo-custom-build.zip)
Download the zip file and run `unzip -d demo-custom-build demo-custom-build.zip && cd demo-custom-build/demo-custom-build && npm i && npm run css`
Error:
```
CssSyntaxError: /Users/ju/Downloads/demo-custom-build/node_modules/boosted/scss/mixins/_utilities.scss:82:16: Unclosed bracket
80 |             @if $is-local-vars {
81 |               @each $local-var, $variable in $is-local-vars {
> 82 |                 --#{$prefix}#{$local-var}: #{$variable};
|                ^
83 |               }
84 |             }
```
Now open `node_modules/boosted/scss/mixins/_utilities.scss` and modify it to have the same content …

fix(css): rename `$prefix` in `$func-prefix` in `get-color-from-rgba-string` function

---

site/content/docs/5.2/content/images.md

Just a quick modification about the `title` used for the example of "Image thumbnails" that was referencing the old style of image thumbnails.

fix(docs): bad title for 'Image thumbnails' example

---

scss/_tags.scss
site/content/docs/5.2/components/tags.md

Missing one vendor prefix for Chrome in order to display close button correctly.
We saw with @louismaximepiton that the close button inside some tags was missing in Chrome because there was a vendor prefix missing for this browser.
⚠️ : need to fix it before release by @julien-deramond 
* https://deploy-preview-1574--boosted.netlify.app/docs/5.2/components/tags/

Fix close button inside tags on Chrome

---

scss/_pagination.scss

Closes #1351 
Add breakpoints after lg to avoid what's mentioned in the issue.
* https://deploy-preview-1579--boosted.netlify.app//docs/components/pagination/

fix(paginations): add missing breakpoints after lg

---

site/content/docs/5.2/migration.md

- Latest commit integrated in this list is https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/commit/b7b16d57c35bb1352ac114776359f1df3c4ee5e8
- :warning: If the markups are modified in the documentation, it could mean that something should be integrated in the migration guide
- Try to add temporarily a comment next to the new sentence in order for the reviewers to be able to go directly to the commit in Bootstrap or Boosted. Example is done for the back to top component
/cc @louismaximepiton

Prepare migration guide v5.2.0 → v5.2.1

---

scss/_carousel.scss
scss/_variables.scss

Fixes #1508.
Add an `inspect` function around the used Sass var in order to avoid the trailing spaces around the `/` to avoid it to become a division.
Even if `$enable-rounded` shouldn't be used in the context of Orange, let's try to make things good.
* https://deploy-preview-1604--boosted.netlify.app/

CSS: Fix compilation issue when `$enable-rounded: true`

---

site/content/docs/5.2/customize/color.md

Closes #1356 
- Put the paragraph "Orange's colors" at the very beginning of the page, as the 1st paragraph of the page
- In the paragraph "All colors", put the text "All Boosted colors are available as Sass variables and a Sass map..." in an ODS warning message.
This issue comes from the work done in Issue #1201 
Update doc only
* https://deploy-preview-1610--boosted.netlify.app/docs/5.2/customize/color/

Customize/colors : Move Orange's colors paragraph and add warning

---

scss/forms/_form-check.scss

Closes #1576 
Force the `background-position` to cover a height of 100%.
* https://deploy-preview-1612--boosted.netlify.app/docs/5.2/forms/checks-radios/#switches
⚠️ Please review the changes on all platforms/browsers combinations.

fix(forms): switch rendering on some platforms

---

site/content/docs/5.2/components/orange-navbar.md
site/content/docs/5.2/migration.md
site/layouts/shortcodes/orange-global-headers.html
site/layouts/shortcodes/orange-supra.html

Simple accessibility fix.
The name of the buttons must be included in their accessible names.
See [Success Criterion 2.5.3 Label in Name](https://www.w3.org/TR/WCAG21/#label-in-name) for more details.
* [https://deploy-preview-1629--boosted.netlify.app/docs/5.2/components/orange-navbar/#with-additional-navbar](https://deploy-preview-1629--boosted.netlify.app/docs/5.2/components/orange-navbar/#with-additional-navbar)

Fix languages buttons accessible names

---

site/content/docs/5.2/components/navbar.md
site/content/docs/5.2/components/scrollspy.md
site/layouts/partials/docs-navbar.html

Reused `alt` value for Orange logos (created in our Orange navbars) in Navbar and Scrollspy examples, but also in our doc header.
We don't need to mention in the migration guide since it is a value that becomes specific given the usage in a real project.
Uniformization in all the documentation.
* https://deploy-preview-1630--boosted.netlify.app (documentation header)
* https://deploy-preview-1630--boosted.netlify.app/docs/5.2/components/navbar/ (some examples with Orange logo)
* https://deploy-preview-1630--boosted.netlify.app/docs/5.2/components/scrollspy/ (some examples with Orange logo)

fix(docs): uniformize `alt` value for Orange logos

---

scss/forms/_form-range.scss

Fixes #1606 
Change the calculation to position the input range thumb on Webkit.
TBH I haven't checked on all browsers. Dear reviewer, could you help me doing that 🙏
* https://deploy-preview-1632--boosted.netlify.app/docs/5.2/forms/range/

fix(range): realign input range thumb margin on Webkit

---

config.yml
site/content/docs/5.2/extend/icons.md

Linked to #901.
Changed the link to Solaris Icons to redirect on the DSM directly
Redirect people on the DSM is the best.
* https://deploy-preview-1634--boosted.netlify.app/docs/extend/icons

Changing the link to Solaris icons

---

.eslintignore
.gitignore
package.json

Linked to the following issue mentioned in https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/1626:
Error message when running `npm run storybook-build` and then `npm run storybook`
```
...
> boosted@5.2.1 docs-vnu
> node build/vnu-jar.js
"file:/Users/ju/Orange-Boosted-Bootstrap/_site/storybook/index.html":1.38-1.60: info warning: Self-closing tag syntax in text/html documents is widely discouraged; it's unnecessary and interacts badly with other HTML features (e.g., unquoted attribute values). If you're using a tool that injects self-closing tag syntax into all void elements, without any option to prevent it from doing so, then consider switching to a different tool.
"file:/Users/ju/Orange-Boosted-Bootstrap/_site/storybook/index.html":1.87-^C
```
This error is generated …

fix(storybook): generate SB website in `_site` intead of `site`

---

site/content/docs/5.2/components/navbar.md

Orange logo was missing in the scrolling example.
- Empty link was bad for accessibility
- As mentionned by @isabellechanclou in #1437, there was a focus visible on this empty link.
* [https://deploy-preview-1664--boosted.netlify.app/docs/5.2/components/navbar/#scrolling](https://deploy-preview-1664--boosted.netlify.app/docs/5.2/components/navbar/#scrolling)

Navbar scrolling: fix missing logo

---

scss/_modal.scss

Fixes #1602 
Removed rule to prevent scrollable modals to not having bottom margin on last paragraph of modal-body (in contrary of other modals)
Resolves design problem of having a two big margin at the bottom of scrollable modals
* https://deploy-preview-1661--boosted.netlify.app/docs/5.2/components/modal/#scrolling-long-content

Fix content margin at the bottom of scrollable modal

---

build/.pa11yci.json

NA
Adding a parameter to make it work on windows with certain config: 
```sh
Running Pa11y on 123 URLs:
> http://localhost:9001/docs/5.2/about/overview/ - Failed to run
> http://localhost:9001/docs/5.2/getting-started/accessibility/ - Failed to run
> http://localhost:9001/docs/5.2/components/accordion/ - Failed to run
> http://localhost:9001/docs/5.2/components/alerts/ - Failed to run
> http://localhost:9001/docs/5.2/extend/approach/ - Failed to run
> http://localhost:9001/docs/5.2/components/back-to-top/ - Failed to run
> http://localhost:9001/docs/5.2/utilities/background/ - Failed to run
> http://localhost:9001/docs/5.2/components/badge/ - Failed to run
```
Running Puppeteer can be tough on certain windows config. Here the Puppeteer config for `docs-accessibility` should not break …

Script: Removing an issue on certain windows config running `docs-accessibility`.

---

scss/_stepped-process.scss
site/content/docs/5.2/components/stepped-process.md
site/content/docs/5.2/migration.md

Convert link to current step to plain text.
The current step can't be a link because it's the active page. In addition it should not be possible to focus it.
I converted it to plain text by removing the unnecessary `href="#"` attribute.
* [https://deploy-preview-1663--boosted.netlify.app/docs/5.2/components/stepped-process/](https://deploy-preview-1663--boosted.netlify.app/docs/5.2/components/stepped-process/)

Stepped process: convert current step to plain text for better accessibility

---

.bundlewatch.config.json
scss/_variables.scss
scss/forms/_form-control.scss
scss/forms/_form-select.scss
scss/forms/_input-group.scss
scss/forms/_labels.scss
scss/forms/_quantity-selector.scss
site/content/docs/5.2/forms/form-control.md
site/content/docs/5.2/forms/input-group.md
site/content/docs/5.2/forms/layout.md
site/content/docs/5.2/forms/select.md
site/content/docs/5.2/migration.md

fix(doc): add small size input example

---

.github/workflows/pa11y.yml
.gitignore
build/.pa11yci.json
package-lock.json
package.json
site/layouts/sitemap.xml

This PR bumps pa11y-ci-reporter-html from 3.0.3 to 4.0.0 (first step before a bump to the latest version).
The [pa11y-ci-reporter-html 4.0.0 changelog](https://gitlab.com/gitlab-ci-utils/pa11y-ci-reporter-html/-/tags/4.0.0) mentions that the CLI interface to post-process Pa11y CI JSON reports is no longer supported.
Meaning that running `npm run docs-pa11y-html` doesn't work anymore and generates the following error: `sh: pa11y-ci-reporter-html: command not found` **locally** or **via GitHub Actions (CI)**.
This PR follows the [migration guide](https://gitlab.com/gitlab-ci-utils/pa11y-ci-reporter-html/-/blob/master/docs/upgrade-guide.md) to update our env.
* Modify `site/layouts/sitemap.xml` to have only:
```xml
<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9" …
```

chore(deps-dev): bump pa11y-ci-reporter-html from 3.0.3 to 4.0.0

---

package-lock.json
package.json

This PR follows https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1707 to finally use the latest version of `pa11y-ci-reporter-html`.
Here are the intermediate versions from 4.0.0 to 5.0.2:
- [5.0.0](https://gitlab.com/gitlab-ci-utils/pa11y-ci-reporter-html/-/tags/5.0.0)
- [5.0.1](https://gitlab.com/gitlab-ci-utils/pa11y-ci-reporter-html/-/tags/5.0.1)
- [5.0.2](https://gitlab.com/gitlab-ci-utils/pa11y-ci-reporter-html/-/tags/5.0.2)
There are only 2 breaking elements in 5.0.0:
- "BREAKING: Dropped support for Node 12 and 17 since end-of-life"
- This change is transparent in our case
- "BREAKING: Updated page reports to use [pa11y-reporter-html-plus](https://www.npmjs.com/package/pa11y-reporter-html-plus) instead of the built-in Pa11y HTML reporter. This includes enhanced …

chore(deps-dev): bump pa11y-ci-reporter-html from 4.0.0 to 5.0.2

---

site/content/docs/5.2/customize/color.md

This PR fixes the alignment of the "Orange color tokens" and "Bootstrap core variables" sections.
Before:
* https://deploy-preview-1731--boosted.netlify.app/docs/5.2/customize/color/#usage

docs: enhance rendering of `scss-docs` in Customize > Color section

---

.bundlewatch.config.json
scss/_button-group.scss
scss/_pagination.scss
scss/_variables.scss
scss/forms/_form-check.scss
scss/forms/_form-range.scss
scss/forms/_input-group.scss
scss/forms/_labels.scss
scss/forms/_quantity-selector.scss
scss/mixins/_caret.scss
site/assets/scss/_boosted.scss
site/assets/scss/_clipboard-js.scss
site/assets/scss/_content.scss
site/assets/scss/_tarteaucitron.scss
site/assets/scss/_variables.scss
site/layouts/shortcodes/anchor.html

> **Warning**
> Must be rebased on _main_ after https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1751 is merged
This PR is linked to https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1751 where we'll merge two commits that could have been complicated to review in the middle of everything:
* https://github.com/twbs/bootstrap/commit/7cb376a8fd2133d28960c3a1a1fa2b5016747bae
* https://github.com/twbs/bootstrap/commit/db60ae0625ee989c8fe08076663759c287207c9a
On top of that, in the same spirit, I got rid of all `$border-width` Boosted direct calls and replaced them by the custom property.
Found out while modifying it that we forgot to remove style in our Boosted docs.

chore(merge): 7cb376a and db60ae0

---

package-lock.json
package.json

Please double-check that there is no regression with this new version of tarteaucitronjs.

chore(deps-dev): bump tarteaucitronjs from 1.9.9 to 1.10.0

---

site/content/docs/5.2/migration.md

[Live preview](https://deploy-preview-1824--boosted.netlify.app/docs/5.2/migration/#components)

fix(docs): use the right heading format for progress bars section in the migration guide

---

.bundlewatch.config.json
scss/_nav.scss
scss/_variables.scss
site/content/docs/5.3/components/navs-tabs.md
site/content/docs/5.3/migration.md

The following commit coming from Bootstrap has been isolated in this PR because of the complexity of the review: https://github.com/twbs/bootstrap/commit/7d9aa9d71602ff6856c02ee9b9d2bacf2ee3d2f4.
The principle here is that "Tabs light" nav is replaced by the variant coming from Bootstrap: "Underline".
"Tabs light" were built based on `--bs-nav-tabs-*` CSS vars. Since we don't use `.nav-tabs` in combination of `.nav-underline` a big part of the content of `.nav-tabs` CSS vars and rules has been copied into `.nav-underline`. I'm not sure I can do better here, but if you have any ideas don't hesitate.
This change also implies a breaking change for the Nested Tabs second row which now uses "Underline" nav.
I wanted to redirect the URLs with anchors between v5.2 and v5.3 but that's not going …

Chore merge 13th of Feb

---

README.md

We need to let our README file in v5.2.3.
After the merge of this PR, let's create a task in https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/1776 to put it back just before the v5.3 release

fix(docs): let README in 5.2.3

---

.bundlewatch.config.json
scss/_variables.scss
scss/forms/_form-control.scss
site/content/docs/5.3/forms/form-control.md
site/content/docs/5.3/migration.md
site/layouts/partials/callouts/warning-color-picker.md

Update color picker design.
Closes #1360 
Compliance to UI Kit v5.
- [https://deploy-preview-1794--boosted.netlify.app/docs/5.3/forms/form-control/#color](https://deploy-preview-1794--boosted.netlify.app/docs/5.3/forms/form-control/#color)
- (NA) My new component is added in Storybook

Update color picker according to UI Kit v5

---

.bundlewatch.config.json
scss/_helpers.scss
scss/_nav.scss
scss/_reboot.scss
scss/_root.scss
scss/_utilities.scss
scss/_variables.scss
scss/helpers/_focus-ring.scss
site/assets/scss/_component-examples.scss
site/content/docs/5.3/customize/css-variables.md
site/content/docs/5.3/helpers/focus-ring.md
site/content/docs/5.3/migration.md
site/data/sidebar.yml

This PR integrates only https://github.com/twbs/bootstrap/commit/9e17b2b34cdec9dce063bba09b01aa9a63e7dd94 because of its complexity and impact on our focus handling in Boosted.
Contrary to what's done in Bootstrap, the `.focus-ring` is only a helper in Boosted. But to make it work, we must exclude its main class from the reboot rules.
⚠️ Double-check in all the documentation that the visible focus still works as expected.
- https://deploy-preview-1838--boosted.netlify.app/docs/5.3/helpers/focus-ring/
- https://deploy-preview-1838--boosted.netlify.app/docs/5.3/customize/css-variables/#focus-variables

chore(merge main): patched commit → 9e17b2b

---

package-lock.json
package.json
scss/_root.scss
scss/_variables-dark.scss
scss/vendor/_rfs.scss
site/assets/scss/_content.scss
site/content/docs/5.3/components/breadcrumb.md
site/content/docs/5.3/components/button-group.md
site/content/docs/5.3/components/dropdowns.md
site/content/docs/5.3/components/popovers.md
site/content/docs/5.3/components/tooltips.md
site/content/docs/5.3/content/reboot.md
site/content/docs/5.3/customize/optimize.md
site/content/docs/5.3/forms/overview.md
site/content/docs/5.3/getting-started/rtl.md
site/content/docs/5.3/getting-started/webpack.md
site/layouts/partials/callouts/danger-async-methods.md
site/layouts/partials/callouts/warning-color-assistive-technologies.md
site/layouts/partials/callouts/warning-input-support.md

> **Warning**
> Must be merged after https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1842
- ⚠️ It's been fixed upstream in a commit coming in one of my next PRs, don't worry :)
- ~~https://github.com/twbs/bootstrap/commit/f692ecdd5b4444860f51fb8c14c0730ce860230e~~: nothing to do since we don't have any flush accordions in Boosted
- ~~https://github.com/twbs/bootstrap/commit/d13c8f625cc8c2741297eb9f61f7a82d2b882149~~: nothing to do here, already got it in Boosted via Dependabot PR
_Stopped just before https://github.com/twbs/bootstrap/commit/d70b5db2e0aee9ea9a7255d28395278876bf53ba which I'll do in a dedicated PR._

Chore merge from da1c968

---

js/src/orange-navbar.js

Replace UK english by US english in docs.
Doc consistency.
- [https://deploy-preview-1874--boosted.netlify.app/](https://deploy-preview-1874--boosted.netlify.app/)
- (na) My change follows accessibility good practices; I have at least run axe
- (na) My change is compatible with responsive display
- (na) I have added JavaScript unit tests to cover my changes
- (na) I have added SCSS unit tests to cover my changes

Fix US Vs UK english

---

site/content/docs/5.3/getting-started/download.md

As mentioned in https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1924#discussion_r1149265079, we forgot somehow to gather a modification from Bootstrap which now use de `current_version` param in the "Getting Started > Download" page. (see https://github.com/twbs/bootstrap/blob/main/site/content/docs/5.3/getting-started/download.md?plain=1)
This PR gathers this same modification.
- https://deploy-preview-1926--boosted.netlify.app/docs/5.3/getting-started/download/#npm
- https://deploy-preview-1926--boosted.netlify.app/docs/5.3/getting-started/download/#yarn

fix(docs): use `current_version` data in Getting Started > Download

---

site/content/docs/5.3/migration.md

This PR suggests talking about "Footer" instead of "Orange Footer" in the migration guide because "Footer" is the name of this component.
Consistency and readability.
- <https://deploy-preview-2042--boosted.netlify.app/>
- (N/A) My new component is added in Storybook
- (N/A) My new component is compatible with RTL
- (N/A) Manually run [BrowserStack tests](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/actions/workflows/browserstack.yml)
- (N/A) Manually test browser compatibility with BrowserStack (Chrome >= 60, Firefox >= 60 (+ ESR), Edge, Safari >= 12, iOS Safari, Chrome & Firefox on Android)
- (N/A) Manually launch [Percy tests](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/actions/workflows/percy.yml)

fix(migration): use the name 'Footer' instead of 'Orange Footer'

---

package-lock.json
package.json

This PR bumps tarteaucitronjs dependency from 1.11.0 to 1.12.0.
The [content of this new release](https://github.com/AmauriC/tarteaucitron.js/compare/v1.11.0...v1.12.0) seems to be transparent for us.
Please double-check there's no regression.

chore(deps): bump tarteaucitronjs from 1.11.0 to 1.12.0

---

.github/workflows/js.yml

Supersedes #2082 by fixing the version to v2 like it is done upstream: https://github.com/twbs/bootstrap/blob/bb92ec707aa607fa4a43f49e75d69ebd67132e2e/.github/workflows/js.yml#L48

chore(deps): fix coverallsapp/github-action to v2

---

site/static/docs/5.3/assets/js/tarteaucitron.services.js

NA
Use the same uri as in https://github.com/AmauriC/tarteaucitron.js/blob/master/tarteaucitron.services.js
Be up to date

Tarteaucitron: fix uri

---

hugo.yml

This PR modifies the URL displayed in the documentation to download Solaris icons from the Design System Manager. The previous one was obsolete.
- https://deploy-preview-2112--boosted.netlify.app/docs/5.3/extend/icons/#solaris

fix(docs): Solaris icons URL

---

scss/forms/_form-check.scss
site/content/docs/5.3/forms/validation.md

[#1715](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/1715)
Designers said that the checkbox label "Agree Terms and Conditions" should be a link towards a "Terms and Conditions" page that the user is supposed to read before checking the box.
As no design specification is available yet, a design review is to be asked.
This changed was required by designers.
- <https://deploy-preview-2002--boosted.netlify.app/docs/5.3/forms/validation/#custom-styles>

Forms>Validation : Add a link to "Terms and conditions" checkboxes

---

scss/_variables.scss
site/content/docs/5.3/utilities/borders.md

https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/2064#discussion_r1252683331
This PR reintegrates `.border-4` and `.border-5` from Bootstrap (see https://twbs-bootstrap.netlify.app/docs/5.3/utilities/borders/#width).
This is not mentioned in the migration guide since it's not to be used for Orange developers.
Alignment between Boosted and Bootstrap.
- <https://deploy-preview-2127--boosted.netlify.app/docs/5.3/utilities/borders/#width>

feat(utilities): add `.border-4` and `.border-5`

---

js/src/carousel.js
js/tests/unit/carousel.spec.js
scss/_alert.scss
scss/_buttons.scss
scss/_carousel.scss
scss/_root.scss
scss/_tags.scss
scss/_toasts.scss
scss/_variables.scss
scss/forms/_form-check.scss
scss/helpers/_chevron-link.scss
scss/mixins/_buttons.scss
site/content/docs/5.3/components/carousel.md
site/content/docs/5.3/customize/css-variables.md
site/content/docs/5.3/migration.md

Closes #1553.
Change all `$boosted-prefix` in favor of `$prefix` to harmonize our framework.
Might be merged for v6 only maybe ?
End user will only have one prefix and not being forced to switch beside two of them.
- Breaking change (fix or feature that would change existing functionality)
- <https://deploy-preview-2129--boosted.netlify.app/>
- (NA) My new component is added in Storybook

SCSS: remove `$boosted-prefix` in favor of `$prefix`

---

.github/PULL_REQUEST_TEMPLATE.md

Just a minor change in the last step mentioned in the PR template. Needs to be merged after the v5.3.0 release. No need for a review.

chore(template): change last release step in PR template

---

site/content/docs/5.3/customize/color-modes.md
site/content/docs/5.3/migration.md
site/layouts/_default/baseof.html
site/layouts/_default/examples.html
site/layouts/partials/docs-navbar.html
site/layouts/partials/header.html

It's that time again... deactivating dark mode for the release v5.3.1. This PR basically reverts https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/2158/files.

docs: deactivate dark mode for release v5.3.1

---

site/content/docs/5.3/customize/color-modes.md
site/content/docs/5.3/migration.md
site/layouts/_default/baseof.html
site/layouts/_default/examples.html
site/layouts/partials/docs-navbar.html
site/layouts/partials/header.html

This PR reverts https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/commit/dc990544ea5be89e0e5ce6843cfc007fdd941449 to display the dark mode in the documentation.

docs: reintroduce dark mode

---

.github/workflows/update-pr-review-in-progress.yml

NA
When a PR is reviewed but not approved while not being already approved once, the associated card should move in the Dev Review in Progress column.
⚠️ The actual solution is far from ideal but we can't check either the card column or get all the card's id in one column yet. I tried to check the codeowners but it seems that it's not feasible at the moment so this workflow might need an update later on.
Automate our processes.

 Workflows: Add automation for github project to pass a PR being reviewed directly in good column

---

.github/workflows/browserstack.yml
.github/workflows/bundlewatch.yml
.github/workflows/cspell.yml
.github/workflows/css.yml
.github/workflows/docs.yml
.github/workflows/js.yml
.github/workflows/lint.yml
.github/workflows/node-sass.yml
.github/workflows/pa11y.yml

This PR drops the `labeled` and `unlabeled` workflows triggers to handle `skip:ci` and `skip:pa11y` GH labels.
The recent workflows added to handle our board add and remove labels which triggers several times all the jobs... Skipping CI jobs is native (source: https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs) so `skip:ci` can be removed safely and is rarely used anyway. There's no native `skip:pa11y` but it's also rarely used so it can be safely removed as well IMO.
- Enhancement (non-breaking change which adds functionality)

chore(workflows): drop skip:ci and skip:pa11y

---

site/content/docs/5.3/examples/download-app/index.html

This PR adds a missing redirection for https://boosted.orange.com/examples/download-app. This kind of redirection is available for all other examples in our doc and is missing for this specific example.
```
$ npm run docs
$ ls _site/examples/download-app # Must be generated
```
- https://deploy-preview-2216--boosted.netlify.app/download-app/
- https://deploy-preview-2216--boosted.netlify.app/examples/download-app/
- https://deploy-preview-2216--boosted.netlify.app/docs/examples/download-app/
- https://deploy-preview-2216--boosted.netlify.app/docs/5.3/examples/download-app/

fix(docs): add missing `/examples/download-app` redirection

---

site/content/docs/5.3/forms/form-control.md

In current documentation, the label for the `disabled` input file is missing a `.is-disabled` class.
Whereas it should look like:
Make all disabled form element consistent across the documentation.
- https://deploy-preview-2222--boosted.netlify.app/docs/5.3/forms/form-control/#file-input
- [na] My change follows accessibility good practices; I have at least run axe
- [na] My change respects the design guidelines defined in [Orange Design System](https://system.design.orange.com/0c1af118d/p/8118d1-web)
- [na] My change is compatible with a responsive display
- [na] I have added JavaScript unit tests to cover my changes
- [na] I have added SCSS unit tests to cover my changes
- [na] My change introduces changes to the documentation and/or I have …

[Doc] Add disabled label to disabled file input

---

site/content/docs/5.3/customize/color-modes.md

Closes #2225
This PR adds a redirection from `/docs/customize/color-modes` to `/docs/x.y/customize/color-modes` as it's done for other pages in 'Customize' section.
- https://deploy-preview-2226--boosted.netlify.app/docs/customize/color-modes (should redirect to https://deploy-preview-2226--boosted.netlify.app/docs/5.3/customize/color-modes

fix(docs): add `/docs/customize/color-modes` redirection

---

.cspell.json
site/content/docs/5.3/getting-started/download.md
site/layouts/_default/examples.html

From there, all Bootstrap's commits are gathered for the v5.3.2.

Chore merge from 256ad91 to 317cb2a

---

scss/_variables-dark.scss

This PR fixes some rendering issues observed for our dark variants where the text color is `rgb(238, 238, 238)`  and should be `white`.
It has been included with the dark mode coming from Bootstrap where there's a switch between `$body-color` and `$body-color-dark` to set `--bs-body-color`. The problem is that `$body-color-dark` was set to `$gray-300` instead of `$white`.
We could have used `--bs-emphasis-color` to fix this issue in all impacted components, but I think this fix is easier to maintain has in the dark mode, we will use a light gray default text color instead of white.
Here's a list of identified components in dark variant having the wrong text color.
⚠️ Please double-check all usages in the framework of `$body-color` and `--bs-body-color` to be sure to not introduce another …

fix(dark variant): some text colors were light gray instead of white

---

scss/_accordion.scss
scss/_root.scss
scss/_variables.scss
site/content/docs/5.3/components/accordion.md

#2223.
Adding the accordion as dark variant
I didn't mention any migration note or w/ever, maybe we should think about a section or something to put everything related to dark mode ?
Moving forward on dark theme components.
- <https://deploy-preview-2259--boosted.netlify.app/docs/5.3/components/accordion>

Dark mode: accordions

---

site/data/sidebar.yml

This PR fixes the sidebar menu icons color which were black on dark mode:
They are now using the body color: black on light mode, light gray on dark mode.

Dark mode: Fix sidebar menu icons color

---

scss/_variables.scss
scss/forms/_star-rating.scss
site/content/docs/5.3/dark-mode.md

Star rating in dark mode, by using existing and one new Sass vars :
| `$form-star-rating-checked-color` | `$accessible-orange` | `var(--#{$prefix}link-hover-color)` |
| `$form-star-rating-unchecked-color` | `$gray-700` | `var(--#{$prefix}secondary-color)` |
| `$form-star-rating-hover-color` | `$black` | `var(--#{$prefix}highlight-bg)` |
| `$form-star-rating-disabled-color` ⚠️| - | `var(--#{$prefix}border-color-translucent)` |
- https://deploy-preview-2275--boosted.netlify.app/docs/5.3/forms/checks-radios#star-rating
- https://deploy-preview-2275--boosted.netlify.app/docs/5.3/dark-mode/#star-rating

Star rating dark mode

---

scss/_root.scss
scss/_variables-dark.scss
scss/_variables.scss

Focus visible used to work fine with global color mode but break on nested themes. So instead of using a CSS var, redefining the variable each time we change the theme does the trick.
Focus visible in dark mode, by using existing and new Sass vars :
| `$focus-visible-inner-color` | `var(--#{$prefix}body-bg)` | `$white` |
| `$focus-visible-outer-color` | `var(--#{$prefix}emphasis-color)` | `$black` |
| `$focus-visible-inner-color-dark` | - | `$black` |
| `$focus-visible-outer-color-dark` | - | `$white` |
- https://deploy-preview-2279--boosted.netlify.app/docs/5.3/dark-mode

Dark mode: handle focus visible

---

scss/_variables.scss
site/content/docs/5.3/dark-mode.md

Form range in dark mode, by using existing Sass vars :
| `$form-range-thumb-bg` | `$white` | `var(--#{$prefix}body-bg)` |
| `$form-range-thumb-border` | `var(--#{$prefix}border-width) solid $black` | `var(--#{$prefix}border-width) solid var(--#{$prefix}highlight-bg)` |
| `$form-range-thumb-hover-bg` | `$black` | `var(--#{$prefix}highlight-bg)` |
| `$form-range-thumb-disabled-bg` | `$gray-500` | `var(--#{$prefix}disabled-color)` |
⚠️ `$form-range-track-box-shadow` has been reset to Bootstrap's it might be done afterwards or outside this PR.
- https://deploy-preview-2277--boosted.netlify.app/docs/5.3/forms/range/
- https://deploy-preview-2277--boosted.netlify.app/docs/5.3/dark-mode/#range

Dark mode: Form range

---

scss/_root.scss
scss/_variables.scss
site/content/docs/5.3/dark-mode.md

Update star rating visual check
Form range in dark mode, by using existing Sass vars :
| `$input-bg` | `$white` | `var(--#{$prefix}body-bg)` |
| `$input-disabled-color` | `$gray-700` | `var(--#{$prefix}placeholder-color)` |
| `$input-color` | `$black` | `var(--#{$prefix}body-color)` |
| `$input-placeholder-color` | `var(--#{$prefix}secondary-color)` | `var(--#{$prefix}placeholder-color)` |
:warning: New CSS var:
| CSS var | Light mode value | Dark mode value |
| :------- | :-----------------: | :----------------: |
| `--bs-placeholder-color` | `#666666` | `#999999` |
It could maybe be replaced by `--bs-tertiary-color` or `--bs-secondary-color` if we don't use it elsewhere.
- …

Dark mode: Form controls

---

scss/_variables.scss

Completes #2259 to make accordion's background transparent like in designs
I juste made it directly transparent, it seems to work...
- https://deploy-preview-2284--boosted.netlify.app/docs/5.3/components/accordions/
- https://deploy-preview-2284--boosted.netlify.app/docs/5.3/dark-mode/#accordions

Dark mode: make accordion's background  transparent

---

scss/_variables.scss
scss/forms/_labels.scss
site/content/docs/5.3/dark-mode.md

Form checks in dark mode, by using existing and new Sass vars :
| `$form-text-color` | `var(--#{$prefix}secondary-color)` | `var(--#{$prefix}placeholder-color)` |
| `$form-label-color` | `null` | `var(--#{$prefix}body-color)` |
| `$form-label-disabled-color` | `$gray-500` | `var(--#{$prefix}disabled-color)` |
| `$form-label-required-color` | - | `var(--#{$prefix}link-hover-color)` |
- https://deploy-preview-2289--boosted.netlify.app/docs/5.3/forms/overview/
- https://deploy-preview-2289--boosted.netlify.app/docs/5.3/forms/form-control/
- https://deploy-preview-2289--boosted.netlify.app/docs/5.3/dark-mode/#labels-required-fields--text

Dark mode: Form labels & texts

---

scss/_sticker.scss
scss/_variables.scss
site/content/docs/5.3/dark-mode.md

This PR handles the dark mode for the Sticker component.
New CSS vars:
- `--#{$prefix}sticker-color: #{$sticker-color};`
New Sass vars:
- `$sticker-color`
- `$sticker-background-color`
- `$sticker-font-weight`
- https://deploy-preview-2288--boosted.netlify.app/docs/5.3/dark-mode/#stickers
- https://deploy-preview-2288--boosted.netlify.app/docs/5.3/components/sticker
- https://deploy-preview-2288--boosted.netlify.app/docs/5.3/examples/stickers/

Dark mode: Stickers

---

scss/_tags.scss
scss/_variables.scss
site/content/docs/5.3/dark-mode.md

Tags in dark mode, by using existing Sass vars :
| `$tag-active-color` | `$white` | `var(--#{$prefix}highlight-color)` |
| `$tag-disabled-color` | `$gray-500` | `var(--#{$prefix}disabled-color)` |
| `$tag-border-color` | `$gray-500` | `var(--#{$prefix}border-color-translucent)` |
| `$tag-active-decoration-color` | `$black` | `var(--#{$prefix}highlight-bg)` ⚠️ strange use of this variable |
⚠️  Added 2 Sass vars and corresponding css vars:
| Sass var | css var | Value |
| `$tag-color` | `var(--#{$prefix}tag-color)` | `var(--#{$prefix}body-color)` |
| `$tag-bg` | `var(--#{$prefix}tag-bg)` | `var(--#{$prefix}body-bg)` |
- …

Dark mode: Tags

---

scss/_spinners.scss
scss/_variables.scss
site/content/docs/5.3/components/spinners.md
site/content/docs/5.3/dark-mode.md

New Sass vars:
- `$spinner-color`
⚠️ Added temporary `data-bs-theme` for buttons containing spinners. This should go if we modify `color:` automatically with `[data-bs-theme]`.
- https://deploy-preview-2290--boosted.netlify.app/docs/5.3/components/spinners/
- https://deploy-preview-2290--boosted.netlify.app/docs/5.3/dark-mode/#spinners

Dark mode: Spinners

---

scss/_variables.scss
scss/forms/_labels.scss
site/content/docs/5.3/dark-mode.md

Form helpers in dark mode, by using new Sass vars :
| `$form-helper-color` | - | `var(--#{$prefix}info)` |
| `$form-helper-icon` | - | `escape-svg($helper-icon)` |
- https://deploy-preview-2291--boosted.netlify.app/docs/5.3/forms/overview/
- https://deploy-preview-2291--boosted.netlify.app/docs/5.3/dark-mode/#ghelper

Dark mode: Form helper

---

scss/_buttons.scss
scss/_dropdown.scss
scss/_variables.scss
scss/mixins/_buttons.scss
site/assets/scss/_tarteaucitron.scss
site/content/docs/5.3/dark-mode.md

The PR might be working, the description is WIP
- https://deploy-preview-2293--boosted.netlify.app/docs/5.3/components/buttons
- https://deploy-preview-2293--boosted.netlify.app/docs/5.3/dark-mode/#buttons

Dark mode: Buttons

---

scss/_variables.scss

This PR extracts unrelated dark mode modifications from https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/2292/files#diff-108a57a50d5ebe203f447ef7bf1e5e53826bdb82baab2baa2b41b4158cdd4d09.

fix(dropdown): add missing `instead of` in Boosted mods

---

scss/_variables.scss
site/content/docs/5.3/dark-mode.md

Dropdowns in dark mode, by using existing Sass vars :
| `$dropdown-link-hover-bg` | `$gray-500` | `var(--#{$prefix}border-color-translucent)` ⚠️ strange use of this variable |
| `$dropdown-link-active-color` | `color-contrast($component-active-color)` | `var(--#{$prefix}highlight-color)` |
| `$dropdown-link-active-bg` | `$component-active-color` | `var(--#{$prefix}highlight-bg)` |
| `$dropdown-link-disabled-color` | `$gray-500` | `var(--#{$prefix}disabled-color)` |
| `$dropdown-header-color` | `$black` | `var(--#{$prefix}body-color)` |
NB: added and completed Boosted mod comments
- https://deploy-preview-2292--boosted.netlify.app/docs/5.3/components/dropdowns/
- …

Dark mode: Dropdowns

---

scss/_variables.scss
site/content/docs/5.3/dark-mode.md

Form input group in dark mode, by using existing Sass vars :
| `$input-group-addon-color` | `null` | `$input-color` |
⚠️ Should stay as `null` or `inherit` imo.
- https://deploy-preview-2299--boosted.netlify.app/docs/5.3/forms/input-group/
- https://deploy-preview-2299--boosted.netlify.app/docs/5.3/dark-mode/#input-group

Dark mode: Input group

---

scss/_variables.scss
site/content/docs/5.3/dark-mode.md

Form file inputs in dark mode, by using existing Sass vars :
| `$form-file-button-bg` | `var(--#{$prefix}body-bg)` | `$input-bg` |
- https://deploy-preview-2295--boosted.netlify.app/docs/5.3/forms/form-control#file-input/
- https://deploy-preview-2295--boosted.netlify.app/docs/5.3/dark-mode/#file-input

Dark mode: File input

---

scss/_variables.scss
scss/forms/_labels.scss

Form checks in dark mode, by using existing and new Sass vars :
| `$form-helper-bg` | - | `var(--#{$prefix}highlight-color)` |
- https://deploy-preview-2305--boosted.netlify.app/docs/5.3/forms/overview#form-helper/
- https://deploy-preview-2305--boosted.netlify.app/docs/5.3/dark-mode/#helper

Dark mode: Add solid bg under `.form-helper`

---

js/tests/unit/carousel.spec.js

This PR suggests changing the markup used to render the play/pause buttons in carousels' unit tests so that they use the same one as in https://boosted.orange.com/docs/5.3/components/carousel/#with-pauseplay-button:
```html
<button type="button" class="btn btn-icon carousel-control-play-pause pause" data-bs-target="#carouselExamplePause" data-bs-play-text="Play Carousel" data-bs-pause-text="Pause Carousel" title="Pause Carousel">
<span class="visually-hidden">Pause Carousel</span>
</button>
```
It basically means to drop the use of `.btn-secondary`.
_Note: it'll help with the work in progress in https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/2223_
Consistency between the carousels' markups.
N/A

fix(unit tests): drop `.btn-secondary` from carousel play/pause buttons

---

scss/_breadcrumb.scss
scss/_root.scss
scss/_variables.scss
site/content/docs/5.3/dark-mode.md

Breadcrumb in dark mode, by using new Sass and CSS vars :
| `$breadcrumb-divider-filter` | - | `var(--#{$prefix}icon-filter)` |
| `$breadcrumb-divider-color` | `null` | `$black` |
⚠️ New CSS var: 
| CSS var | Light value | Dark value |
| `--bs-icon-filter` | `none` | `$invert-filter` |
It means that applying this filter on an icon will transform from black to white depending on the color mode chosen.
- https://deploy-preview-2315--boosted.netlify.app/docs/5.3/components/breadcrumb
- https://deploy-preview-2315--boosted.netlify.app/docs/5.3/dark-mode/#breadcrumb

Dark mode: Breadcrumb

---

.storybook/main.js
.storybook/manager.js
.storybook/preview.js
package-lock.json
package.json

This PR adds a new dev dependency named `@storybook/addon-themes` which allows the addition of a theme switcher within the Storybook interface (see https://storybook.js.org/blog/introducing-theme-switcher-addon/).
This is not directly useful for Boosted team, but could be through ZeroHeight one day.
However, it allows us to be sure that https://github.com/Orange-OpenSource/ods-storybook-theme is working correctly with Boosted components, and this, can be useful for the projects when they develop their components in isolation.
Technically it handles a switch with our `data-bs-theme` attribute.
Be careful, the other button in the toolbar handles the dark mode of the SB interface (so only the background behind the stories right now).

Dark Mode: Storybook addon

---

js/tests/visual/modal.html
site/content/docs/5.3/components/accordion.md
site/content/docs/5.3/components/badge.md
site/content/docs/5.3/components/list-group.md
site/content/docs/5.3/components/orange-navbar.md
site/content/docs/5.3/migration.md
site/content/docs/5.3/utilities/position.md
site/content/docs/5.3/utilities/text.md
site/content/docs/versions.md
site/layouts/shortcodes/orange-global-headers.html
site/layouts/shortcodes/orange-supra.html

Chore: merge from ce11411 to f7426c0

---

scss/_nav.scss
scss/_variables-dark.scss
scss/_variables.scss
site/content/docs/5.3/dark-mode.md

Navs & tabs in dark mode, by using existing Sass vars :
| `$nav-tabs-link-hover-border-color` | `$border-color` | `var(--#{$prefix}highlight-color)`  ⚠️ strange use of this variable |
| `$nav-underline-border-color` | `$gray-500` | `var(--#{$prefix}border-color-translucent)` |
| `$nav-underline-link-active-color` | `var(--#{$prefix}emphasis-color)` | `var(--#{$prefix}hover-color)` |
| `$nav-underline-link-hover-color` | `$accessible-orange` | `var(--#{$prefix}link-hover-color)`  ⚠️ strange use of this variable |
| `$nav-underline-link-active-bg` | `var(--#{$prefix}body-bg)` | `transparent` ❓ do we need to keep these vars ? (only in Boosted) |
| `$nav-underline-link-active-border-color` | …

Dark mode: Navs & tabs

---

scss/_root.scss
scss/_variables.scss
scss/forms/_form-check.scss
site/content/docs/5.3/dark-mode.md

Form checks in dark mode, by using new Sass vars :
| `$form-switch-square-bg` | - | `$black` |
| `$form-switch-bg` | - | `$white` |
| `$form-switch-border-color` | - | `$white` |
| `$form-switch-filter` | - | `var(--#{$prefix}input-filter)` |
| `$form-switch-focus-visible-inner` | - | `$black` |
| `$form-switch-focus-visible-outer` | - | `$white` |
| `$form-switch-checked-square-bg` | - | `var(--#{$prefix}highlight-color)` |
| `$form-switch-checked-bg` | - | `$primary` |
| `$form-switch-checked-border-color` | - | `$primary` |
| `$form-switch-checked-filter` | - | `none` |
| `$form-switch-checked-focus-inner` | - | `var(--#{$prefix}focus-visible-inner-color)` |
| `$form-switch-checked-focus-outer` | - …

Dark mode: Form switch

---

scss/_root.scss
scss/_variables-dark.scss
scss/_variables.scss
scss/forms/_form-select.scss
site/content/docs/5.3/dark-mode.md

Form checks in dark mode, by using existing and new Sass vars :
**Indicates the color value of the icon:**
| `$form-select-disabled-color` | `$gray-700` | `$input-disabled-color` |
| `$form-select-indicator` | - | - |
| `$form-select-disabled-indicator` | `$form-select-disabled-color` | `#666666` |
| `$form-select-indicator-dark` | - | `#ffffff` |
| `$form-select-disabled-indicator-dark` | - | `#999999` |
:warning: New CSS vars:
**Indicates the color value of the icon:**
| CSS var | Light mode value | Dark mode value |
| :------- | :-----------------: | :----------------: |
| `--bs-select-indicator` | `#000000` | `#ffffff` |
| `--bs-select-disabled-indicator` | `#666666` | `#999999` |
- …

Dark mode: Form select

---

scss/_variables.scss
scss/forms/_quantity-selector.scss
site/content/docs/5.3/dark-mode.md

Form checks in dark mode, by using new Sass vars :
| `$quantity-selector-disabled-color` | - | `var(--#{$prefix}disabled-color)` |
| `$quantity-selector-disabled-bg` | - | `var(--#{$prefix}body-bg)` |
| `$quantity-selector-button-bg` | - | `var(--#{$prefix}body-bg)` |
| `$quantity-selector-button-border` | - | `var(--#{$prefix}border-width) solid var(--#{$prefix}border-color-translucent)` |
- https://deploy-preview-2287--boosted.netlify.app/docs/5.3/forms/quantity-selector/
- https://deploy-preview-2287--boosted.netlify.app/docs/5.3/dark-mode/#quantity-selector

Dark mode: Quantity selector

---

scss/_variables.scss
site/content/docs/5.3/dark-mode.md

Close button in dark mode, by using existing Sass vars :
| `$btn-close-active-color` | `$primary` | `var(--#{$prefix}link-hover-color)` |
| `$btn-close-active-border-color` | `$gray-500` | `var(--#{$prefix}border-color-translucent)` |
| `$btn-close-disabled-color` | `$gray-500` | `var(--#{$prefix}disabled-color)` |
- https://deploy-preview-2317--boosted.netlify.app/docs/5.3/components/close-button
- https://deploy-preview-2317--boosted.netlify.app/docs/5.3/dark-mode/#close-button

Dark mode: Close button

---

scss/mixins/_forms.scss
site/content/docs/5.3/forms/validation.md

Spotted in https://deploy-preview-2302--boosted.netlify.app/docs/5.3/dark-mode/#form-validation while working on the dark mode, the rendering of the form control color when the feedback is valid is odd:
The purple area should be square like for the other states.
This PR fixes it to have this unified rendering whatever the states:
While we were working on this issue, we spotted another issue that is linked to the right-padding of the valid icon which was too important. With this PR, this padding has the same value (for all form controls) as the top/bottom padding.
Only the left padding of the input is bigger, but this is probably by design.
Some issues have been created based on the development of this one:
- https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/2342
- Bug …

fix(form-control-color): adjust size when valid feedback

---

scss/_root.scss
scss/_variables-dark.scss
scss/_variables.scss
scss/mixins/_forms.scss
site/content/docs/5.3/dark-mode.md

Form validation in dark mode, by using existing and new Sass vars :
| `$success-icon-dark` | - | `url(...)` |
| `$danger-icon-dark` | - | `url(...)` |
| `$form-valid-color-dark` | `$green-300` | `var(--#{$prefix}succes-text-emphasis)` |
| `$form-valid-border-color-dark` | `$green-300` | `var(--#{$prefix}success)` |
| `$form-invalid-color-dark` | `$red-300` | `var(--#{$prefix}danger-text-emphasis)` |
| `$form-invalid-border-color-dark` | `$red-300` | `var(--#{$prefix}danger)` |
| `$form-feedback-color` | - | `var(--#{$prefix}body-color)` |
:warning: New values for CSS vars:
| CSS var | Light mode value | Dark mode value |
| :------- | :-----------------: | :----------------: |
| `--bs-success-icon` | …

Dark mode: Form validation

---

scss/_variables.scss
site/content/docs/5.3/dark-mode.md

Modals in dark mode, by using existing Sass vars :
| `$popover-header-color` | `$headings-color` | `var(--#{$prefix}heading-color)` |
| `$headings-color` | `inherit` | `$black` |
⚠️ Need a `data-bs-theme="body"` somehow ?
⚠️ Change in `$headings-color` and probably need to check everything that depends from that (`var(--#{$prefix}heading-color)`, etc...)
- https://deploy-preview-2325--boosted.netlify.app/docs/5.3/components/popovers
- https://deploy-preview-2325--boosted.netlify.app/docs/5.3/dark-mode/#popovers

Dark mode: Popovers

---

scss/_pagination.scss
scss/_variables.scss
site/content/docs/5.3/dark-mode.md

⚠️ Removing the focus state of the pagination. Might be done on main branch before ?
Pagination in dark mode, by using existing Sass vars :
| `$pagination-color` | `null` | `var(--#{$prefix}link-color)` |
| `$pagination-bg` | `var(--#{$prefix}body-bg)` | `transparent` |
| `$pagination-hover-bg` | `null` | `var(--#{$prefix}active-bg)` |
| `$pagination-hover-border-color` | `$gray-500` | `$pagination-hover-bg` |
| `$pagination-active-color` | `$white` | `var(--#{$prefix}highlight-color)` |
| `$pagination-active-bg` | `$black` | `var(--#{$prefix}highlight-bg)` |
| `$pagination-disabled-color` | `$gray-500` | `var(--#{$prefix}disabled-color)` |
| `$pagination-disabled-bg` | `$white` | `transparent` |
| …

Dark mode: Pagination

---

scss/_carousel.scss
scss/_variables.scss
site/content/docs/5.3/dark-mode.md

⚠️ Modified `$headings-color` from `inherit` to `$black`
Carousel in dark mode, by using existing and new Sass vars :
| `$headings-color` | `inherit` | `$black` |
| `$carousel-control-icon-color` | - | `$black` |
| `$carousel-caption-color` | `$black` | `var(--#{$prefix}body-color)` |
| `$carousel-caption-bg` | - | `var(--#{$prefix}body-bg)` |
- https://deploy-preview-2316--boosted.netlify.app/docs/5.3/components/carousel
- https://deploy-preview-2316--boosted.netlify.app/docs/5.3/dark-mode/#carousel

Dark mode: Carousel

---

scss/_variables.scss
site/content/docs/5.3/components/card.md
site/content/docs/5.3/content/figures.md
site/content/docs/5.3/content/images.md
site/content/docs/5.3/dark-mode.md
site/content/docs/5.3/examples/cards-rtl/index.html
site/content/docs/5.3/examples/cards/index.html
site/content/docs/5.3/examples/masonry/index.html
site/content/docs/5.3/layout/columns.md
site/content/docs/5.3/utilities/borders.md
site/content/docs/5.3/utilities/object-fit.md
site/layouts/shortcodes/card.html
site/layouts/shortcodes/placeholder.html

Cards in dark mode, by using existing Sass vars :
| `$card-cap-bg` | `$black` | `var(--#{$prefix}highlight-bg)` |
| `$btn-close-active-border-color` | `$white` | `var(--#{$prefix}highlight-bg)` |
| `$btn-close-disabled-color` | `$gray-700` | `var(--#{$prefix}placeholder-color)` |
- https://deploy-preview-2318--boosted.netlify.app/docs/5.3/components/card
- https://deploy-preview-2318--boosted.netlify.app/docs/5.3/dark-mode/#card

Dark mode: Cards

---

site/assets/scss/_search.scss

Algolia modal in dark mode.
- https://deploy-preview-2338--boosted.netlify.app/docs/

Dark mode: Algolia modal

---

package-lock.json
package.json

This PR bumps `tarteaucitronjs` dev dep from 1.14.0 to 1.15.0.
I analyzed the [diff between 1.14.0 and 1.15.0](https://github.com/AmauriC/tarteaucitron.js/compare/v1.14.0...v1.15.0) and couldn't spot any impacting modifications, even if some enhancements have been done on the CSS side.
Here's the rendering before:
Here's the new rendering:
The only difference is the breakline which is not defined in ODS anyway. So let's continue to keep what's from tac.

chore(deps-dev): bump `tarteaucitronjs` from 1.14.0 to 1.15.0

---

scss/_variables.scss
site/content/docs/5.3/components/progress.md
site/content/docs/5.3/dark-mode.md

Progress bars in dark mode, by using existing Sass vars :
| `$progress-bg` | `var(--#{$prefix}secondary-bg)` | `var(--#{$prefix}active-bg)` |
| `$progress-bar-color` | `$black` | `var(--#{$prefix}highlight-color)` |
| `$progress-bar-bg` | `$primary` | `var(--#{$prefix}link-hover-color)` |
⚠️ Need a check on all colors of this progress before going to review.
:warning: Not quite sure to use the right variables here.
- https://deploy-preview-2326--boosted.netlify.app/docs/5.3/components/progress
- https://deploy-preview-2326--boosted.netlify.app/docs/5.3/dark-mode/#progress

Dark mode: Progress bars

---

scss/_tooltip.scss

This PR fixes __tooltip.scss_ that contained two CSS vars with a double prefix.
- <https://deploy-preview-2353--boosted.netlify.app/>

fix(tooltips): two CSS vars had a double prefix

---

scss/_variables.scss
site/content/docs/5.3/dark-mode.md
site/data/palette.yml

List group in dark mode, by using existing Sass vars :
| `$list-group-bg` | `var(--#{$prefix}body-bg)` | `transparent` |
| `$list-group-active-color` | `$white` | `var(--#{$prefix}highlight-color)` |
| `$list-group-active-bg` | `$black` | `var(--#{$prefix}highlight-bg)` |
| `$list-group-disabled-color` | `$gray-500` | `var(--#{$prefix}disabled-color)` |
| `$list-group-action-color` | `$black` | `$list-group-color` |
| `$list-group-action-hover-color` | `$primary` | `var(--#{$prefix}link-hover-color)` |
- https://deploy-preview-2321--boosted.netlify.app/docs/5.3/components/list-group
- https://deploy-preview-2321--boosted.netlify.app/docs/5.3/dark-mode/#list-group

Dark mode: List group

---

js/src/quantity-selector.js
js/tests/unit/quantity-selector.spec.js
scss/_variables.scss
scss/forms/_quantity-selector.scss
scss/mixins/_forms.scss
site/content/docs/5.3/forms/quantity-selector.md
site/content/docs/5.3/forms/validation.md
site/content/docs/5.3/migration.md

Coming from the separation of old #1949 PR into two distinct, more comprehensible and easier to review/maintain PR.
This PR is coming alongside with the work on the insufficient contrast in form error state (PR #2090) and was needed after the suggestions made by our design team during Spec meeting - June, 13.
When on error and focused, we must keep the wole borders for the input in the middle and for the buttons.
So we must go from this:
to this:
(same for buttons)
Improve a11y and design unity.
- <https://deploy-preview-2099--boosted.netlify.app/docs/5.3/forms/quantity-selector/>
- <https://deploy-preview-2099--boosted.netlify.app/docs/5.3/forms/validation/#supported-elements>
- (NA) I have added JavaScript unit tests to cover …

Fix quantity selector focus state

---

site/content/docs/5.3/examples/navbars/index.html
site/layouts/shortcodes/orange-global-headers.html

This PR fixes the rendering of the minimized use case in Navbars example page by removing the `minimized` parameter from the `orange-navbar` shortcode.
- https://deploy-preview-2354--boosted.netlify.app/docs/5.3/examples/navbars/

fix(examples): apply correctly `.header-minimized` to the Navbars example

---

scss/_root.scss
scss/_variables.scss
site/content/docs/5.3/content/tables.md
site/content/docs/5.3/dark-mode.md

⚠️ Need to determine whether we have a transparent bg or a solid bg (nesting).
⚠️ If solid bg: Need to determine whether we keep `#141414` or `#000000` in dark mode.
⚠️ Need to determine whether the `.table-active` is the most important state or the `:hover` state.
⚠️ Might be merged after https://github.com/twbs/bootstrap/pull/38826 to properly handle `.bg-transparent` on it.
Tables in dark mode, by using existing Sass vars :
| `$table-bg` | `var(--#{$prefix}body-bg)` | `transparent` |
| `$table-striped-bg` | `$table-striped-bg-factor` | `var(--#{$prefix}table-striped-bg-factor)` |
| `$table-striped-hover-color` | `$table-color` | `var(--#{$prefix}black)` |
| `$table-striped-hover-bg` | …

Dark mode: Tables

---

scss/_reboot.scss
scss/_root.scss
scss/_variables.scss
site/content/docs/5.3/dark-mode.md

⚠️ Adding `color-scheme` for a great rendering of basic inputs.
⚠️ We could drop all those `.text-body` classes and some more changes in `_reboot.scss` to revert once #2313 is merged.
⚠️ Need to determine whether the file input is not working from a mistake of us or a browser issue ?
Basic elements in dark mode, by using existing Sass var :
| `$pre-color` | `var(--#{$prefix}pre-color, $gray-900)` | `var(--#{$prefix}body-color-subtle)` |
⚠️ New CSS var :
| CSS var | Light value | Dark value |
| `--bs-body-color-subtle` | `$gray-900` | `$gray-300` |
- https://deploy-preview-2355--boosted.netlify.app/docs/5.3/content/reboot
- …

Dark mode: basic elements

---

scss/_footer.scss
scss/_variables.scss
site/content/docs/5.3/components/orange-navbar.md
site/content/docs/5.3/dark-mode.md
site/content/docs/5.3/examples/download-app/index.html
site/content/docs/5.3/examples/form/index.html
site/layouts/partials/footer.html
site/layouts/shortcodes/orange-footer.html
site/layouts/shortcodes/orange-global-headers.html

⚠️ Need to determine if we keep the Download-app page hover text decoration or the form page one (A11y would prefer the download-app page one).
⚠️ We'll probably need a `.border-translucent` or whatever changes border from `#cccccc` in light mode to `#666666` in dark mode (might bring some more breaking changes for the markup).
Footers in dark mode, by using existing and new Sass vars :
| `$footer-color` | - | `var(--#{$prefix}body-color)` |
| `$footer-accordion-active-color` | `$brand-orange` | `var(--#{$prefix}link-hover-color)` |
⚠️ Deprecated `$footer-nav-link-font-weight`
⚠️ Change the markup from the footer: `footer.footer.bg-dark.navbar-dark` -> `footer.footer.navbar[data-bs-theme="dark"]`
- …

Dark mode: Footer

---

scss/_title-bars.scss
scss/_variables.scss
site/content/docs/5.3/components/title-bars.md
site/content/docs/5.3/dark-mode.md
site/content/docs/5.3/examples/title-bars/index.html

Title bars in dark mode, by using existing and new Sass vars :
| `$title-bar-bg` | - | `var(--#{$prefix}body-bg)` |
| `$title-bar-color` | - | `var(--#{$prefix}body-color)` |
| `$title-bar-border-color` | `$gray-500` | `var(--#{$prefix}border-color-translucent)` |
⚠️ Deprecated `$title-bar-border-color-dark`
⚠️ New CSS var that could be avoided by #2313: `--bs-title-bar-bg` & `--bs-title-bar-color`
- https://deploy-preview-2350--boosted.netlify.app/docs/5.3/components/title-bars
- https://deploy-preview-2350--boosted.netlify.app/docs/5.3/dark-mode/#title-bars

Dark mode: Title bars

---

scss/_type.scss
scss/_variables.scss
site/content/docs/5.3/migration.md

This PR fixes the `.lead` values (font-size, line-height and letter-spacing) for this class to match the [body text definition in the DSM's design token](https://design.orange.com/0c1af118d/p/68dbd8-typography/t/095277) (`ods.web.sys.font.body.m`).
This is needed for projects willing to have a less condensed rendering for articles for instance.
They are the following:
| Size | font-size | line-height | letter-spacing |
|---|---|---|---|
| Desktop | 20px | 1.5=30px | -0.40px | 
| Tablet | 18px | 1.5=27px | -0.20px | 
| Mobile | 16px | 1.5=24px | -0.10px |
The review must double-check these 3 values for each size: desktop, mobile and tablet.
- https://deploy-preview-2363--boosted.netlify.app/docs/5.3/content/typography/#lead
- …

fix(typography): modify `.lead` values to match the DSM body text

---

js/tests/visual/dropdown.html
scss/_button-group.scss
scss/_buttons.scss
scss/_dropdown.scss
site/assets/scss/_content.scss
site/content/docs/5.3/components/button-group.md
site/content/docs/5.3/components/dropdowns.md
site/content/docs/5.3/components/offcanvas.md
site/content/docs/5.3/customize/color-modes.md
site/content/docs/5.3/dark-mode.md
site/content/docs/5.3/forms/input-group.md

Dropped `:not(.toggle-plit-dropdown)` rule inside `.dropdown-toggle` and introduce it as `.btn-dropdown`
Searched for every `.dropdown-toggle` and related `.btn-secondary` and decide whether it's a `.toggle-split-dropdown`, it should change to the new `.btn-dropdown` or let it as Bootstrap:
- `CHANGELOG.md`: nothing to do.
- `js/src/scrollspy.js`: nothing to do.
- `js/src/tab.js`: nothing to do.
- `js/tests/unit/dropdown.spec.js`: nothing to do.
- `js/tests/unit/tab.spec.js`: nothing to do.
- `js/tests/visual/dropdown.html`:
- `.btn-secondary.dropdown-toggle` -> `.btn-dropdown.dropdown-toggle`
- Added some `.dropdown-toggle-split` where needed to have the good rendering.
- `js/tests/visual/scrollspy.html`: nothing to do.
- `scss/_button-group.scss`: nothing to do
- `scss/_dropdown.scss`: …

Dark mode: Dropdown variant

---

site/assets/scss/_callouts.scss

Proposal to make docs callouts more highlighted than before in light and dark mode.
- https://deploy-preview-2375--boosted.netlify.app/docs/5.3/docsref

Dark mode: Make docs callouts more highlighted

---

site/layouts/_default/examples.html

Added the new `.btn-drdopdown`, `.dropup` and removed `.opacity-50`.
Some changes might be done on Bs side afterwards.
- https://deploy-preview-2381--boosted.netlify.app/docs/5.3/examples/download-app

Dark mode: Render the color theme switcher well

---

site/assets/scss/_component-examples.scss
site/assets/scss/_variables.scss
site/layouts/shortcodes/example.html
site/layouts/shortcodes/js-docs.html
site/layouts/shortcodes/scss-docs.html

Proposal to make docs code highlights less highlighted in dark mode. Adding some small changes in the borders as well.
Refactor Ratio examples to better fit dark mode. This change should be done anyway.
- https://deploy-preview-2378--boosted.netlify.app/docs/5.3/docsref
- https://deploy-preview-2378--boosted.netlify.app/docs/5.3/helpers/ratios

Dark mode: Proposals to handle dark mode code highlights

---

site/assets/scss/_component-examples.scss
site/assets/scss/_toc.scss
site/assets/scss/_variables.scss
site/content/docs/5.3/utilities/spacing.md
site/layouts/partials/home/get-started.html

⚠️ Removal of `--bd-primary` and `--bd-primary-rgb`
Need to check the table of content (right menu) scrollspy as well
- https://deploy-preview-2371--boosted.netlify.app/docs/5.3/utilities/z-index
- https://deploy-preview-2371--boosted.netlify.app/docs/5.3/layout/columns
- https://deploy-preview-2371--boosted.netlify.app/docs/5.3/layout/grid
- https://deploy-preview-2371--boosted.netlify.app/docs/5.3/helpers/stacks
- https://deploy-preview-2371--boosted.netlify.app/docs/5.3/helpers/vertical-rule
- https://deploy-preview-2371--boosted.netlify.app/docs/5.3/utilities/flex
- https://deploy-preview-2371--boosted.netlify.app/docs/5.3/utilities/sizing

Dark mode: handle orange in the doc

---

scss/_badge.scss
scss/_buttons.scss
scss/_variables-dark.scss
scss/helpers/_color-bg.scss
site/content/docs/5.3/components/badge.md
site/content/docs/5.3/components/list-group.md
site/content/docs/5.3/components/orange-navbar.md
site/content/docs/5.3/components/progress.md
site/content/docs/5.3/dark-mode.md
site/layouts/shortcodes/orange-global-headers.html
site/layouts/shortcodes/orange-supra.html

⚠️ Adjusted the colors of `.text-bg-*` in dark mode (use the same trick as outlined buttons. Might be just temporary.
⚠️ Functional colors changed in dark mode.
Check all the list below to ensure everything is greatly colored.
- https://deploy-preview-2370--boosted.netlify.app/docs/5.3/components/badge
- https://deploy-preview-2370--boosted.netlify.app/docs/5.3/components/buttons
- https://deploy-preview-2370--boosted.netlify.app/docs/5.3/components/list-group/#with-badges
- https://deploy-preview-2370--boosted.netlify.app/docs/5.3/components/orange-navbar
- https://deploy-preview-2370--boosted.netlify.app/docs/5.3/components/progress/#backgrounds
- https://deploy-preview-2370--boosted.netlify.app/docs/5.3/forms/validation
- https://deploy-preview-2370--boosted.netlify.app/docs/5.3/forms/o …

Dark mode: Change functionnal colors in dark mode

---

site/assets/scss/_boosted.scss

Add a micro animation as there was before on the DSM.
Anyway the color change might be done on dark mode branch.
- https://deploy-preview-2379--boosted.netlify.app/docs/5.3/guidelines

Docs: Micro anim on docs guidelines page

---

site/content/docs/5.3/dark-mode.md

This PR adds the badge component in the /dark-mode page as a sub-task listed in https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/2223.
Note: Setting `data-bs-theme` directly onto the component when only defined as a `<span>` + `.text-bg-{color}` doesn't work at all times; the text color is not always the right color. This is due to the fact that, at the time of the creation of this PR, the color and background color are not automatically changed with `data-bs-theme`.
- https://deploy-preview-2387--boosted.netlify.app/docs/5.3/dark-mode/#badge

Dark mode: add badge in /dark-mode page

---

scss/_maps.scss
scss/_variables.scss
scss/forms/_form-check.scss
site/assets/scss/_colors.scss
site/content/docs/5.3/utilities/colors.md

⚠️ To be rebased and merged after https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/2382
This PR replaces `$accessible-orange` with `$primary`. Its value is defined by `$ods-orange-200`.
- N/A

Dark mode: remove `$accessible-orange`

---

hugo.yml
site/layouts/partials/docs-navbar.html
site/layouts/partials/footer.html

This PR changes the URL of the Solaris icons to `https://oran.ge/icons` which was broken, but also adds this link in the header and footer of our documentation.
Since the link was broken, a follow-up PR will be created targeting _gh-pages_ to fix this issue.
- <https://deploy-preview-2396--boosted.netlify.app/docs/extend/icons>

Solaris icons: Change the access url.

---

docs/5.0/examples/cheatsheet/cheatsheet.css
docs/5.0/examples/cheatsheet/cheatsheet.rtl.css
docs/5.0/extend/icons/index.html
docs/5.1/examples/cheatsheet/cheatsheet.css
docs/5.1/examples/cheatsheet/cheatsheet.rtl.css
docs/5.1/extend/icons/index.html
docs/5.2/extend/icons/index.html
docs/5.3/extend/icons/index.html

This PR follows up https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/2396 by fixing the Solaris icons URL by replacing the old ones with the new generic one.

fix: change Solaris icons URLs in previous versions

---

site/content/docs/5.3/examples/masonry/index.html

This PR tackles the following sub-task defined in https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/2223 description:
> The rendering is rather clear on the whole page except maybe the black card. Let's use a `.text-bg-secondary` and a `.text-tertiary` for the fig caption
Note: There was a typo so I used `.text-body-tertiary` instead.
- https://deploy-preview-2408--boosted.netlify.app/docs/5.3/examples/masonry/

Dark mode: fix black card in masonry example

---

site/content/docs/5.3/components/spinners.md

This PR tackles the following sub-task defined in https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/2223 description:
> Remove `data-bs-theme="dark"` for buttons containing spinners. This should go if we modify `color:` automatically with `[data-bs-theme]`. Otherwise, the only solution would be to have something like `.text-body-inverted` that we want to avoid.
- https://deploy-preview-2410--boosted.netlify.app/docs/components/spinners/#buttons

Dark mode: Spinners doc fix

---

site/content/docs/5.3/migration.md

This PR tackles the following sub-task of https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/2140:
> Think to modify https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/2158/commits/983d0eb36d96e6508a7c9520a1b3814a10f29263 if needed
I've only gathered the second message as the first one is not useful for a migration.
- https://deploy-preview-2413--boosted.netlify.app/docs/5.3/migration/#v530

Dark mode: enhance Color Modes v5.3.0 explanation in migration guide

---

site/content/docs/5.3/examples/download-app/download-app.css

As decided this 14th of December during the core team meeting by designers, a11y team, and developers, this PR removes the underlined hovered effect of the footer links in our Download page example for consistency.
This implementation will be done via https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/2407 in the future if this is accepted as the right solution.
- https://deploy-preview-2415--boosted.netlify.app/docs/5.3/examples/download-app/

fix(examples): drop underline of hovered footer links in Download page example

---

scss/_root.scss
scss/_variables-dark.scss
scss/_variables.scss
scss/forms/_form-check.scss

This PR tackles the following sub-task defined in https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/2223 description:
> All new CSS variables in _root.scss that are Boosted-specific should be set by a specific Sass variable instead of using Sass colors directly (reference https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/2382#discussion_r1425039339)
Make sure that the variables are well named and well placed.
- https://deploy-preview-2409--boosted.netlify.app/dark-mode/

Dark mode: introduce new Sass variables

---

scss/_variables.scss

#2223
Issue with focus on select.
Not quite sure about the solution, maybe we can drop the firefox specific rule for the select ?
We can't see the select once focused on it.
- <https://deploy-preview-2404--boosted.netlify.app/docs/examples/form>

Dark mode: select fix

---

scss/_local-navigation.scss
scss/_nav.scss
scss/_root.scss
scss/_variables-dark.scss
scss/_variables.scss
site/content/docs/5.3/components/local-navigation.md
site/content/docs/5.3/dark-mode.md

This PR safely removes `--bs-nav-link-active-color`.
Following design private conversation: 
>  regarding the Local navigation Selected state Label, the label should change to White on the dark mode version with the orange underline. This would make it consistent with the Light mode version.
> 
> the Hover states should be the same on both the light and dark mode versions. The hover state should use an orange coloured label.
> 
> the same changes should be applied to the Tabs Underline component selected and hover states in light and dark modes.
The artboards have been updated.
I tweaked a bit the associated CSS to follow these new rules. (Less Generated CSS)
Should be transparent for users (apart for the look).
- https://deploy-preview-2406--boosted.netlify.app/docs/5.3/dark-mode/#local-n …

Dark mode: Local nav and nav underline fix

---

scss/_root.scss
scss/_tables.scss
scss/_variables-dark.scss
scss/_variables.scss
scss/mixins/_table-variants.scss
site/content/docs/5.3/content/tables.md

Following the design updates for the dark mode.
⚠️ These changes might be breaking for users. I think it's feasible to make it non-breaking but it means more difficult to maintain + Keep some useless CSS in our Bundle.
⚠️ The striped rows are going from `#f6f6f6` (eq: `$gray-200`) to `#000000` (eq: `$black`). It's almost `--bs-tertiary-bg`
⚠️ Should we remove dark variant (or at least from all examples) ? Seeing the doc in dark mode feels really weird
- https://deploy-preview-2418--boosted.netlify.app/docs/dark-mode/#tables
- https://deploy-preview-2418--boosted.netlify.app/docs/content/tables

Dark mode: Table fix

---

site/content/docs/5.3/components/toasts.md
site/content/docs/5.3/dark-mode.md

Tweaked a bit the documentation to be consistent.
Remaining question from the dark mode PR description:
> Need to have `data-bs-theme="inverted"` for `.*bg-secondary` (toasts color schemes)? 
- https://deploy-preview-2380--boosted.netlify.app/docs/5.3/components/toasts
- https://deploy-preview-2380--boosted.netlify.app/docs/5.3/dark-mode/#toasts

Dark mode: Toasts

---

site/content/docs/5.3/components/navbar.md

This PR tackles the following sub-task:
> Check that tasks in https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/2140 have been done. This issue tracks dark mode reverts we'll need to do when the dark mode will be implemented:
> Revisit this Bootstrap section (https://getbootstrap.com/docs/5.3/components/navbar/#color-schemes) in Boosted which is hidden for now but could work when we'll get rid of .navbar-dark and replace it with data-bs-theme="dark"
This idea is to render the examples to show how `.navbar-dark` is no longer useful and how it works now with the `data-bs-theme` attribute.
Please note that these 3 examples are not exactly the ones from Bootstrap and are slightly adapted to look like actual Boosted navbars.
I haven't add them into a `<details><summary>` …

Dark mode: Navbar Color Schemes

---

scss/_variables.scss
site/assets/scss/_content.scss
site/content/docs/5.3/components/spinners.md

This PR tackles the following sub-task identified in #2140:
> Check modifications in https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/2030 (most of the one linked to the text colors must be reverted)
This PR contains the only elements I've found to modify that were extra temporary elements coming from this PR. The dark mode implementation already took care of the majority of them by removing mostly extra `.text-*` classes.
- https://deploy-preview-2414--boosted.netlify.app/docs/5.3/customize/color-modes/#custom-color-modes

Dark mode: revert some changes linked to `main` temporary `.text-*` utilities usage before dark mode

---

site/content/docs/5.3/components/list-group.md

This PR fixes the list group documentation where `.list-group-item-Success` kind of classes were used instead of `list-group-item-success` due to the changes we made in the YML files.
- https://deploy-preview-2435--boosted.netlify.app/docs/5.3/components/list-group/#variants

Dark mode: fix list group documentation

---

site/content/docs/5.3/utilities/background.md

This PR tackles the following sub-task defined in https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/2223 description:
> **Background**
> Doc: explain the rules between  `.bg-primary|success|etc.` and `.bg-supporting-*` (how to use them)
Texts might need to be rewrote.
- https://deploy-preview-2411--boosted.netlify.app/docs/utilities/background

Dark mode: Docs about background utility

---

site/content/docs/5.3/components/orange-navbar.md
site/content/docs/5.3/utilities/colors.md

This PR adds a warning callout to the "Orange's colors" section to precise that the light mode rules must be applied when a text can be seen on both light and dark backgrounds.
This was a sub-task identified in https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/2223:
> Colors: Rework docs/5.3/utilities/colors/#oranges-colors to explain it clearly
- https://deploy-preview-2444--boosted.netlify.app/docs/5.3/utilities/colors/#oranges-colors

Dark mode: add a warning callout to Orange's colors section

---

site/content/docs/5.3/migration.md

Chore merge main from 8cc86cc to 11272ec

---

.eslintignore
.eslintrc.json
js/src/modal.js
js/src/scrollspy.js
js/src/tooltip.js
js/src/util/backdrop.js
js/tests/unit/carousel.spec.js
js/tests/unit/dropdown.spec.js
js/tests/unit/modal.spec.js
js/tests/unit/offcanvas.spec.js
js/tests/unit/orange-navbar.spec.js
js/tests/unit/quantity-selector.spec.js
js/tests/unit/scrollspy.spec.js
js/tests/unit/tab.spec.js
js/tests/unit/toast.spec.js
js/tests/unit/tooltip.spec.js
package-lock.json
package.json
scss/_accordion.scss
scss/_buttons.scss

- Note: I've added a new commit at the end of the process (https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/2474/commits/6bb61132dc276961adc5bf606aa5717bf7c5de50) because `js-lint` wasn't checking JS files 🙃 I've fixed the files in error and excluded `/stories/create-stories-from-doc.js` that contained too much errors linked to await and stuff; too risky to fix)

Chore merge main from 52cc934 to 4e35f64

---

docs/5.2/components/navbar/index.html
docs/5.2/components/orange-navbar/index.html

As you can see in https://boosted.orange.com/docs/5.2/components/orange-navbar/, we can observe some "There's a newer version of Boosted!" messages directly into the Orange navbar examples:
This was introduced with the big global modification in https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/2147/files#diff-5b9361e477624c95d541b93c9998e5d724eac117b7e31273dae93593cfdd2932.
I haven't found any other occurrences in other versions of our documentation.

fix(docs): remove extra 'new version' messages in Orange navbar examples from the v5.2

---

js/src/dom/selector-engine.js
js/tests/unit/dom/selector-engine.spec.js
js/tests/unit/modal.spec.js
package-lock.json
package.json
site/content/docs/5.3/getting-started/parcel.md
site/content/docs/5.3/getting-started/vite.md
site/content/docs/5.3/getting-started/webpack.md

Chore merge from d30385b to c396a2a

---

.github/PULL_REQUEST_TEMPLATE.md
hugo.yml
site/content/docs/5.3/guidelines/_index.md
site/data/design-guidelines.yml
site/layouts/_default/single.html
site/layouts/partials/home/orange-design-system.html

NA
Use `oran.ge/*` links when possible.
Being more flexible to changes inside the DSM and so avoid broken links.
- <https://deploy-preview-2488--boosted.netlify.app/>
- (NA) My new component is well displayed in [Storybook](https://deploy-preview-2488--boosted.netlify.app/storybook)
- (NA) Manually run [BrowserStack tests](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/actions/workflows/browserstack. …

Docs: Use oran.ge links when they exist

---

site/content/docs/5.3/extend/icons.md

This PR adds a section explaining how icons are built/rendered within a square and with a safe zone.
In projects, we are often wondering whether this safe zone is normal or not. Some designers in the projects remove them, some keep them. The purpose here is to fix this rule in our documentation.
- Enhancement (non-breaking change which adds functionality)
- https://deploy-preview-2217--boosted.netlify.app/docs/5.3/extend/icons/#icons-rendering

docs: add Icons rendering section

---

.bundlewatch.config.json
js/src/carousel.js

(NA)
To align with the way Bootstrap handle and manage CSS class names in JS, I propose to add dedicated variable for boosted mod play/pause CLASS_NAME_PAUSE
CLASS_NAME_PLAY
Would help if a custom project wants to prefix his CSS classes _for example_
- <https://deploy-preview-2502--boosted.netlify.app/>

Use constant to define play/pause css class names for caroussel

---

package-lock.json
package.json
site/assets/js/tac.js

This PR bumps tarteaucitronjs dependency from 1.16.1 to 1.17.0.
This new version brings some new features that are mentioned in the [corresponding release note](https://github.com/AmauriC/tarteaucitron.js/releases/tag/v1.17.0).
From this changelog, some elements to look at precisely.
This PR adds the new `googleConsentMode` parameter and set it to `false`. With `true` (default value), the cookies are not stored anymore.
This PR adds the new `partnersList` parameter and set it to `true`. With Google Tag Manager, it doesn't seem to display more information, but it could be useful in the future if we add other services.
We apparently don't need to call it ourselves since it's used by the new save button already.
This new save button needed to have a Boosted-style so this PR adds some classes …

chore(deps): bump tarteaucitronjs from 1.16.1 to 1.17.0

---

.github/dependabot.yml

NA
Add a group to `dependabot.yml`
Ease of maintenance
NA
- (NA) I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)
- (NA) My change follows accessibility good practices; I have at least run axe
- (NA) My change respects the design guidelines defined in [Orange Design System](https://oran.ge/dsweb)
- (NA) My change is compatible with a responsive display
- (NA) My change follows the [developer guide](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/wiki/Developer-guide)
- …

Deps: Group dependabot PRs for Storybook

---

package-lock.json
package.json

Based on https://github.com/AmauriC/tarteaucitron.js/releases/tag/v1.19.0:

chore(deps-dev): bump tarteaucitronjs from 1.18.0 to 1.19.0

---

.storybook/preview-head.html

This PR changes the location of the `docs.css` loaded by Storybook. Given the fact that our OUDS Web documentation is not yet deployed, [I've temporarily created the right file in our `gh-pages` branch](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/commit/5c1ab621ab9c9b66210cfd375080dd1669afd131) as it will help with testing for our first releases/deployments.

Docs(storybook): load a temp OUDS Web docs 0.1 CSS asset

---

.github/workflows/notify.yml

Surprisingly, this `notify.yml` GH workflow has been launched after publishing OUDS Web v0.0.1. We don't need Mattermost notifications for now, so this PR comments out the content of this file until it's reintegrated at the right moment.

[OUDS] chore(workflows): comment content of notify.yml

---

composer.json

This PR doesn't change anything to our v4 version. It's only there to silent the Packagist errors sent for each Packagist updates:
```
Reading composer.json of orange-opensource/orange-boosted-bootstrap (v4-dev)
Importing branch v4-dev (dev-v4-dev)
Skipped branch v4-dev, Invalid package information: 
replace.orange-opensource/orange-boosted-bootstrap : a package cannot set a replace on itself
```

fix(composer): drop 'replace' property

---

README.md

There were errors mentioned at https://packagist.org/packages/orange-opensource/orange-boosted-bootstrap and received by emails as error notifications too.
These have been supposedly fixed.
This PR updates the command mentioned in our README file.
The name provided in our current `ouds/main` for Composer is `"name": "orange-opensource/ouds-web",`, targetting the future repository URL.
It means that, in the meantime, there won't be any `vx.y.z-ouds-web` Composer versions at https://packagist.org/packages/orange-opensource/orange-boosted-bootstrap.
We don't have many users, so the solution, for now is to provide the reference of our main OUDS Web branch.
Locally, you can test to run: `composer require orange-opensource/orange-boosted-bootstrap:dev-ouds/main`:
```
./composer.json has been …
```

[OUDS] Fix(README): composer command line

---

README.md

This PR fixes the "npm version" badge present in our README. Indeed, it was configured to use the non-scoped version of the package we defined earlier.
The rich diff can show the before/after rendering: https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/2634/files?short_path=b335630#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5
The PR also removes the Packagist badge as we're not deploying yet our package there.

fix(README): npm version badge

---

site/content/docs/0.0/migration-from-boosted.md

This PR adds some information about the new namings in the Boosted migration page.
- https://deploy-preview-2637--boosted.netlify.app/docs/0.0/migration-from-boosted/

[OUDS] Docs: add new files names in Boosted migration page

---

js/tests/karma.conf.js

This PR tries to trigger BrowserStack tests. They should fail but with a new build name. 
**Results:** 
- The build name is well changed, search for `ouds-web-` in https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/actions/runs/10041403964/job/27749411325
- The CI is still triggered manually
- The tests still fail

[OUDS] CI/CD: Browserstack tests

---

js/src/scrollspy.js
js/src/toast.js
scss/_dropdown.scss
scss/_navbar.scss
scss/_root.scss
scss/_utilities.scss
scss/_variables.scss
site/content/docs/0.0/migration-from-boosted.md

This PR handles the "deprecate" comments in JavaScript and Sass files.
The rules are the following:
- If the deprecation comment comes from Bootstrap, keep it and include the word "Bootstrap" in it
- If the deprecation comment comes from Boosted and relies on Bootstrap values, change it to OUDS Web, and keep the Boosted previous values for Boosted projects migrating to OUDS Web
- If the deprecation comment comes from Boosted only, the corresponding variable(s) can be removed from the framework
All removed Sass variables are listed in the Boosted migration guide.

[OUDS] Css: drop deprecated Boosted variables and change deprecated comments

---

site/content/docs/0.0/extend/approach.md
site/data/sidebar.yml

This PR adds the "Getting Started > Contribute" page based on:
- the previous [corresponding Boosted page](https://boosted.orange.com/docs/5.3/extend/approach/) (see [code source](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/site/content/docs/5.3/extend/approach.md))
- the [corresponding Bootstrap page](https://getbootstrap.com/docs/5.3/extend/approach/) (see [code source](https://github.com/twbs/bootstrap/blob/main/site/content/docs/5.3/extend/approach.md))
Please that not all content can be reintroduced in this first PR, as some components or concepts are not yet described in the rest of the documentation.
- …

[OUDS] docs: add 'Extend > Approach' page

---

site/content/docs/0.0/utilities/flex.md
site/data/sidebar.yml

This PR adds the **Utilities > Flex** page based on:
- the previous [corresponding Boosted page](https://boosted.orange.com/docs/5.3/utilities/flex/) (see [code source](https://raw.githubusercontent.com/Orange-OpenSource/Orange-Boosted-Bootstrap/main/site/content/docs/5.3/utilities/flex.md))
- the [corresponding Bootstrap page](https://getbootstrap.com/docs/5.3/utilities/flex/) (see [code source](https://raw.githubusercontent.com/twbs/bootstrap/main/site/content/docs/5.3/utilities/flex.md))
To help the review, please note that the content of this page is exactly the same as [the one from Boosted](https://raw.githubusercontent.com/Orange-OpenSource/Orange-Boosted-Bootstrap/main/site/content/docs/5.3/utiliti …

[OUDS] Docs(utilities): add 'Flex' page

---

site/content/docs/0.0/utilities/vertical-align.md
site/data/sidebar.yml

This PR adds the "Utilities > Vertical align" page based on:
- the previous [corresponding Boosted page](https://boosted.orange.com/docs/5.3/utilities/vertical-align/) (see [code source](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/site/content/docs/5.3/utilities/vertical-align.md))
- the [corresponding Bootstrap page](https://getbootstrap.com/docs/5.3/utilities/vertical-align/) (see [code source](https://github.com/twbs/bootstrap/blob/main/site/content/docs/5.3/utilities/vertical-align.md))
- https://deploy-preview-2668--boosted.netlify.app/docs/0.0/utilities/vertical-align/

[OUDS] Docs: add 'Utilities > Vertical align' page

---

site/content/docs/0.0/utilities/object-fit.md
site/data/sidebar.yml

This PR adds the "Utilities > Object fit" page based on:
- the previous [corresponding Boosted page](https://boosted.orange.com/docs/5.3/utilities/object-fit/) (see [code source](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/site/content/docs/5.3/utilities/object-fit.md))
- the [corresponding Bootstrap page](https://getbootstrap.com/docs/5.3/utilities/object-fit/) (see [code source](https://github.com/twbs/bootstrap/blob/main/site/content/docs/5.3/utilities/object-fit.md))
The remaining code will be added once the responsive part of the CSS is added in the OUDS Web CSS.
`.rounded` could be reintegrated if rounded is imported in OUDS Web
- New documentation (non-breaking change …

[OUDS] Docs: add 'Utilities > Object fit' page

---

site/content/docs/0.0/helpers/text-truncation.md
site/data/sidebar.yml

Listed in #2589.
This PR adds the "Helpers > Text truncation" page based on:
- the previous [corresponding Boosted page](https://boosted.orange.com/docs/5.3/helpers/text-truncation/) (see [code source](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/site/content/docs/5.3/helpers/text-truncation.md))
- the previous [corresponding Bootstrap page](https://getbootstrap.com/docs/5.3/helpers/text-truncation/) (see [code source](https://github.com/twbs/bootstrap/blob/main/site/content/docs/5.3/helpers/text-truncation.md))
- <https://deploy-preview-2670--boosted.netlify.app/docs/0.0/helpers/text-truncation/>

[OUDS] Docs: add 'Helpers > Text truncation' page

---

site/content/docs/0.0/utilities/overflow.md
site/data/sidebar.yml

This PR adds the "Utilities > Overflow" page based on:
- the previous [corresponding Boosted page](https://boosted.orange.com/docs/5.3/utilities/overflow/) (see [code source](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/site/content/docs/5.3/utilities/overflow.md))
- the [corresponding Bootstrap page](https://getbootstrap.com/docs/5.3/utilities/overflow/) (see [code source](https://github.com/twbs/bootstrap/blob/main/site/content/docs/5.3/utilities/overflow.md))
- https://deploy-preview-2664--boosted.netlify.app/docs/0.0/utilities/overflow/

[OUDS] Docs: add 'Utilities > Overflow' page

---

site/content/docs/0.0/utilities/interactions.md
site/data/sidebar.yml

This PR adds the "Utilities > Interactions" page based on:
- the previous [corresponding Boosted page](https://boosted.orange.com/docs/5.3/utilities/interactions/) (see [code source](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/site/content/docs/5.3/utilities/interactions.md))
- the [corresponding Bootstrap page](https://getbootstrap.com/docs/5.3/utilities/interactions/) (see [code source](https://github.com/twbs/bootstrap/blob/main/site/content/docs/5.3/utilities/interactions.md))
- https://deploy-preview-2662--boosted.netlify.app/docs/0.0/utilities/interactions/

[OUDS] Docs: add 'Utilities > Interactions' page

---

site/content/docs/5.3/utilities/overflow.md

Following #2664.
Change `.bg-white` to `.bg-body` to handle dark mode.
This change was introduced by https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/1751/files#diff-dbf24c07dc13b7fbbb26a7a91a4d9abfad4ba4a385cf00de0c327d6461034b2a and it seems like it went out of our vision for a long time now.
- <https://deploy-preview-2671--boosted.netlify.app/docs/utilities/overflow>

Docs: Overflow remove `.bg-white`

---

site/content/docs/0.0/utilities/float.md
site/data/sidebar.yml

This PR adds the "Utilities > Float" page based on:
- the previous [corresponding Boosted page](https://boosted.orange.com/docs/5.3/utilities/float/) (see [code source](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/site/content/docs/5.3/utilities/float.md))
- the [corresponding Bootstrap page](https://getbootstrap.com/docs/5.3/utilities/float/) (see [code source](https://github.com/twbs/bootstrap/blob/main/site/content/docs/5.3/utilities/float.md))
The remaining code will be added once the responsive part or the clearfix helper of the CSS is added in the OUDS Web CSS.
- …

[OUDS] Docs: add 'Utilities > Float' page

---

site/content/docs/0.0/utilities/api.md
site/content/docs/0.0/utilities/position.md
site/data/sidebar.yml

This PR adds the "Utilities > Position" page based on:
- the previous [corresponding Boosted page](https://boosted.orange.com/docs/5.3/utilities/position/) (see [code source](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/site/content/docs/5.3/utilities/position.md))
- the [corresponding Bootstrap page](https://getbootstrap.com/docs/5.3/utilities/position/) (see [code source](https://github.com/twbs/bootstrap/blob/main/site/content/docs/5.3/utilities/position.md))
The remaining code will be added once the button part or text background helper and the border utility will be added in the OUDS Web CSS.
- …

[OUDS] Docs: add 'Utilities > Position' page

---

site/content/docs/0.0/helpers/position.md
site/data/sidebar.yml

This PR adds the "Helper > Position" page based on:
- the previous [corresponding Boosted page](https://boosted.orange.com/docs/5.3/helpers/position/)(see [code source](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/site/content/docs/5.3/helpers/position.md))
- the [corresponding Bootstrap page](https://getbootstrap.com/docs/5.3/helper/position/) (see [code source](https://github.com/twbs/bootstrap/blob/main/site/content/docs/5.3/helper/position.md))
The remaining code will be added once the responsive part of the CSS is added in the OUDS Web CSS.
- https://deploy-preview-2672--boosted.netlify.app/docs/0.0/helpers/p …

[OUDS] Docs: Add 'Helper > Position' page

---

site/content/docs/0.0/helpers/clearfix.md
site/content/docs/0.0/utilities/float.md
site/data/sidebar.yml

Listed in #2589.
This PR adds the "Helpers > Clearfix" page based on:
- the previous [corresponding Boosted page](https://boosted.orange.com/docs/5.3/helpers/clearfix/) (see [code source](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/site/content/docs/5.3/helpers/clearfix.md))
- the previous [corresponding Bootstrap page](https://getbootstrap.com/docs/5.3/helpers/clearfix/) (see [code source](https://github.com/twbs/bootstrap/blob/main/site/content/docs/5.3/helpers/clearfix.md))
- <https://deploy-preview-2673--boosted.netlify.app/docs/0.0/helpers/clearfix/>

[OUDS] Docs: add 'Helpers > Clearfix' page

---

site/content/docs/0.0/helpers/visually-hidden.md
site/data/sidebar.yml

Listed in #2589.
This PR adds the "Helpers > Visually hidden" page based on:
- the previous [corresponding Boosted page](https://boosted.orange.com/docs/5.3/helpers/visually-hidden/) (see [code source](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/site/content/docs/5.3/helpers/visually-hidden.md))
- the previous [corresponding Bootstrap page](https://getbootstrap.com/docs/5.3/helpers/visually-hidden/) (see [code source](https://github.com/twbs/bootstrap/blob/main/site/content/docs/5.3/helpers/visually-hidden.md))
- <https://deploy-preview-2674--boosted.netlify.app/docs/0.0/helpers/visually-hidden/>

[OUDS] Docs: add 'Helpers > Visually Hidden' page

---

site/content/docs/5.3/components/badge.md
site/content/docs/5.3/components/buttons.md
site/content/docs/5.3/components/close-button.md
site/content/docs/5.3/components/orange-navbar.md
site/content/docs/5.3/components/tags.md
site/content/docs/5.3/components/title-bars.md
site/content/docs/5.3/components/tooltips.md
site/content/docs/5.3/content/tables.md
site/content/docs/5.3/dark-mode.md
site/content/docs/5.3/examples/download-app/index.html
site/content/docs/5.3/examples/form/index.html
site/content/docs/5.3/examples/stickers/index.html
site/content/docs/5.3/examples/tags/index.html
site/content/docs/5.3/extend/icons.md
site/content/docs/5.3/migration.md
site/layouts/shortcodes/card.html
site/layouts/shortcodes/orange-footer.html
site/layouts/shortcodes/orange-global-headers.html
site/layouts/shortcodes/orange-supra.html
site/layouts/shortcodes/placeholder.html

Closes #2677 
This PR drops `focusable="false"` for SVGs since we don't support Internet Explorer anymore.
- Accessibility enhancement (non-breaking change)
- <https://deploy-preview-2678--boosted.netlify.app/>

docs(a11y): drop `focusable='false'` for SVGs

---

site/content/docs/0.0/layout/css-grid.md
site/data/sidebar.yml

Listed in #2589.
This PR adds the "Layout > Css Grid" page based on:
- the previous [corresponding Boosted page](https://boosted.orange.com/docs/5.3/layout/css-grid/) (see [code source](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/site/content/docs/5.3/layout/css-grid.md))
- the previous [corresponding Bootstrap page](https://getbootstrap.com/docs/5.3/layout/css-grid/) (see [code source](https://github.com/twbs/bootstrap/blob/main/site/content/docs/5.3/layout/css-grid.md))
**Please note** that the responsive part is commented, since the main responsive documentation page is not yet available.
The bs-gap value presented in this documentation is also commented since the value is not set yet.
- …

[OUDS] Docs: add 'Layout > Css grid' page

---

site/content/docs/5.3/getting-started/introduction.md

NA
Change the title level.
Better a11y.
- <https://deploy-preview-2680--boosted.netlify.app/docs>

Docs: "Getting started > Introduction" fix typo

---

site/content/docs/0.0/utilities/display.md
site/data/sidebar.yml

This PR adds the "Utilities > Display" page based on:
- the previous [corresponding Boosted page](https://boosted.orange.com/docs/5.3/utilities/display/) (see [code source](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/site/content/docs/5.3/utilities/display.md))
- the [corresponding Bootstrap page](https://getbootstrap.com/docs/5.3/utilities/display/) (see [code source](https://github.com/twbs/bootstrap/blob/main/site/content/docs/5.3/utilities/display.md))
The remaining code will be added once the responsive part of the CSS is added in the OUDS Web CSS.
- …

[OUDS] Docs: add 'Utilities > Display' page

---

site/content/docs/0.0/utilities/z-index.md
site/data/sidebar.yml
site/layouts/partials/docs-sidebar.html

This PR adds the "Utilities > Z-index" page based on:
- the previous [corresponding Boosted page](https://boosted.orange.com/docs/5.3/utilities/z-index/) (see [code source](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/site/content/docs/5.3/utilities/z-index.md))
- the [corresponding Bootstrap page](https://getbootstrap.com/docs/5.3/utilities/z-index/) (see [code source](https://github.com/twbs/bootstrap/blob/main/site/content/docs/5.3/utilities/z-index.md))
The remaining code will be added once the z-index component overlays will be added in the OUDS Web CSS.
`.rounded-3` could be reintegrated when the border-radius will be reintegrated in OUDS Web.
- New documentation …

[OUDS] Docs: add 'Utilities > Z-index' page

---

site/content/docs/0.0/getting-started/introduction.md
site/data/sidebar.yml

This PR adds the "Getting started > Introduction" page based on:
- the previous [corresponding Boosted page](https://boosted.orange.com/docs/5.3/getting-started/introduction/) (see [code source](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/site/content/docs/5.3/getting-started/introduction.md))
- the [corresponding Bootstrap page](https://getbootstrap.com/docs/5.3/getting-started/introduction/) (see [code source](https://github.com/twbs/bootstrap/blob/main/site/content/docs/5.3/getting-started/introduction.md))
⚠️ Needs to merge- :warning: : 
- ~~Does the type need to be added to the CSS to display the page ? IMO we can keep as-is (and add the codepen demo when the type is …

[OUDS] docs: add 'Getting started > Introduction' page

---

site/content/docs/0.0/getting-started/accessibility.md
site/data/sidebar.yml

This PR adds the "Getting Started > Accessibility" page based on:
- the previous [corresponding Boosted page](https://boosted.orange.com/docs/5.3/getting-started/accessibility/) (see [code source](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/site/content/docs/5.3/getting-started/accessibility.md))
- the [corresponding Bootstrap page](https://getbootstrap.com/docs/5.3/getting-started/accessibility/) (see [code source](https://github.com/twbs/bootstrap/blob/main/site/content/docs/5.3/getting-started/accessibility.md))
Please that not all content can be reintroduced in this first PR, as some components or concepts are not yet described in the rest of the documentation.
There are …

[OUDS] Docs: Add 'Getting started > Accessibility' page

---

site/content/docs/0.0/helpers/stacks.md
site/data/sidebar.yml

This PR adds the "Helpers > Stacks" page based on:
- the previous [corresponding Boosted page](https://boosted.orange.com/docs/5.3/helpers/stacks/) (see [code source](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/site/content/docs/5.3/helpers/stacks.md))
- the [corresponding Bootstrap page](https://getbootstrap.com/docs/5.3/helpers/stacks/) (see [code source](https://github.com/twbs/bootstrap/blob/main/site/content/docs/5.3/helpers/stacks.md))
- Uncomment elements whenever `/helpers/vertical-rule` is added
- Uncomment elements whenever buttons are developed
- Uncomment elements whenever inputs are developed
- …

[OUDS] Docs(helpers): add 'Stacks' page

---

site/content/docs/0.0/getting-started/browsers-devices.md
site/data/sidebar.yml

This PR adds the "Getting started > Browsers & devices" page based on:
- the previous [corresponding Boosted page](https://boosted.orange.com/docs/5.3/getting-started/browsers-devices/) (see [code source](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/site/content/docs/5.3/getting-started/browsers-devices.md))
- the [corresponding Bootstrap page](https://getbootstrap.com/docs/5.3/getting-started/browsers-devices/) (see [code source](https://github.com/twbs/bootstrap/blob/main/site/content/docs/5.3/getting-started/browsers-devices.md))
- https://deploy-preview-2684--boosted.netlify.app/docs/0.0/getting-started/browse …

[OUDS] Docs: Add 'Getting started > Browsers & devices' page

---

site/content/docs/0.0/getting-started/contents.md
site/content/docs/0.0/getting-started/introduction.md
site/data/sidebar.yml

This PR adds the "Getting started > Contents" page based on:
- the previous [corresponding Boosted page](https://boosted.orange.com/docs/5.3/getting-started/contents/) (see [code source](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/site/content/docs/5.3/getting-started/contents.md))
- the [corresponding Bootstrap page](https://getbootstrap.com/docs/5.3/getting-started/contents/) (see [code source](https://github.com/twbs/bootstrap/blob/main/site/content/docs/5.3/getting-started/contents.md))
- https://deploy-preview-2685--boosted.netlify.app/docs/0.0/getting-started/content

Docs: Add 'Getting started > Contents' page

---

site/content/docs/5.3/getting-started/contents.md

This PR updates the end of the 'Contents' page to retrieve the upstream paragraph available at https://raw.githubusercontent.com/twbs/bootstrap/main/site/content/docs/5.3/getting-started/contents.md.
The directory mentioned for the docs wasn't accurate, and finally, Bootstrap content works well for our repository as well. So let's keep the upstream content for an easier maintenance.
- Documentation (non-breaking change)
- <https://deploy-preview-2686--boosted.netlify.app/docs/5.3/getting-started/contents/>

docs(getting started): update 'Contents' page

---

site/layouts/shortcodes/design-callout-alert.html

#2667 issue 1-2
Change the `<div>` with a semantic `<p>` tag, so that the text and link of the design callouts is included into something. No visual change.
Accessibility issue from the audit, see #2667 
- <https://deploy-preview-2722--boosted.netlify.app/docs/getting-started/introduction/>

Fix a11y audit: All texts must be included in a semantic tag (design callouts)

---

package-lock.json
package.json

This PR supersedes https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/pull/2724 as pa11y tests are not executed in Dependabot PRs.
There are some things we need to test before merging this PR:
- See https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/actions/runs/10830125620/job/30049176670?pr=2735.
- "Upload accessibility results" have been skipped as there are no errors 
-  `npm run docs ; npm run docs-accessibility` and `file:///Users/xxx/Orange-Boosted-Bootstrap/.pa11y/index.html` is clean
- [CI results](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/actions/runs/10830594602/job/30050696323?pr=2735)
- `npm run docs ; npm run docs-accessibility`

chore(deps-dev): bump pa11y-ci-reporter-html from 6.0.2 to 7.0.0

---

scss/_maps.scss
scss/_variables.scss
scss/tests/customize/_ouds-web-bootstrap.test.scss
scss/tokens/_semantic.scss
site/content/docs/0.0/migration-from-boosted.md
site/content/docs/0.0/migration.md
site/content/docs/0.0/utilities/borders.md

The references have changed for the border width semantic tokens.
The new semantic border width tokens are:
| Name | Value |
| ---- | ----- |
| border-width-none | border-width-0 |
| border-width-default | border-width-25 |
| border-width-thin | border-width-25 |
| border-width-medium | border-width-50 |
| border-width-thick | border-width-75 |
| border-width-thicker | border-width-100 |
| border-width-outside-focus | border-width-50 |
In summary:
* `border-width-thickest` doesn't exist anymore
* `border-width-medium` is new
* `border-width-interactive-primary-focus` doesn't exist anymore
* `border-width-outside-focus` is new
* `border-width-thick` has a different value
* `border-width-thicker` has a different value

[OUDS] feat: update border width semantic tokens with new references and values

---

scss/_functions.scss
scss/_ouds-maps.scss
scss/_variables.scss
scss/tokens/_raw.scss
scss/tokens/_semantic.scss
site/content/docs/0.0/migration-from-boosted.md
site/content/docs/0.0/migration.md

We finally decided to (re)introduce `$ouds-border-radius-9999` that comes from Figma.
This value is set to `2000px` so we needed to transform it to `125rem`. Hence, the creation of a new `px-to-rem` Sass function, that will be useful for other use cases in the future.
- https://deploy-preview-2751--boosted.netlify.app/docs/0.0/utilities/borders/#sizes

feat: introduce `$ouds-border-radius-9999` raw token and create a `px-to-rem` Sass function

---

scss/forms/_labels.scss

Closes #2758
This PR fixes the issue described at #2758 where the asterisk showing that a form control is required can be alone on a new line when the label length has exactly the same length as the corresponding input.
I tried different non-working solutions based on `word-wrap` and non breakable space without success. This PR relies on @jacques-lebourgeois's suggestion.
The only drawback I've found of this fix is that the asterisk, intead of going to the new line, stays on the same line but is displayed in the safe area; outside of the bounding box that we should use. However, I'd consider that as a minor issue.
See:
- https://deploy-preview-2760--boosted.netlify.app/docs/5.3/forms/overview/#required-field

fix(forms): avoid .is-required element to be alone on a new line

---

.github/dependabot.yml
CODE_OF_CONDUCT.md
composer.json
site/content/docs/5.3/getting-started/introduction.md
site/data/core-team.yml

Dropping myself from the repository 😢 
<details>
<summary>Change a CodePen: Done</summary>
⚠️ In the introduction page, we have the following:
> Get started by including Boosted's production-ready CSS and JavaScript via CDN without the need for any build steps. See it in practice with this [Boosted CodePen demo](https://codepen.io/julien-deramond/pen/WNMxywB).
It would be nice if some of you could fork this CodePen demo and change in this PR the new URL 👌 
</details>
- Documentation update
- https://deploy-preview-2798--boosted.netlify.app/docs/5.3/about/team/

chore: update maintainers information

---

scss/_maps.scss
scss/_utilities.scss
scss/_variables.scss
scss/tests/customize/_ouds-web-bootstrap-utilities.test.scss
site/assets/scss/_callouts.scss
site/assets/scss/_component-examples.scss
site/content/docs/0.0/content/reboot.md
site/content/docs/0.0/utilities/borders.md
site/content/docs/0.0/utilities/position.md
site/content/docs/0.0/utilities/text.md
site/layouts/shortcodes/example.html
site/layouts/shortcodes/js-docs.html
site/layouts/shortcodes/scss-docs.html

NA
:warning: Questions:
Tasks:
The following was done in the PR:
- Added new border color utilities
- Added paragraph about the colors inside borders page
- Changed all the `.border-*` calls in the doc
- Changed all the `border(|color):` calls in the not components
- <https://deploy-preview-2823--boosted.netlify.app/docs/utilities/borders#color>

[OUDS] Add border color utilities to the Colors tokens PR

---

site/content/docs/5.3/examples/download-app/index.html

#2792 
Change alt attributes on images to:
- match the image text content
- have separate alt attributes on two different images
Improve accessibiliy
- <https://deploy-preview-2835--boosted.netlify.app/docs/5.3/examples/download-app/>
Close #2792

fix(examples): bad and duplicated alt names on images

---

.bundlewatch.config.json
js/tests/visual/modal.html
scss/helpers/_color-bg.scss
site/content/docs/0.0/helpers/color-background.md
site/content/docs/0.0/migration-from-boosted.md
site/content/docs/0.0/migration.md
site/content/docs/0.0/utilities/background.md
site/content/docs/0.0/utilities/colors.md
site/content/docs/0.0/utilities/display.md
site/content/docs/0.0/utilities/position.md
site/content/docs/0.0/utilities/text.md
site/content/docs/versions.md
site/data/sidebar.yml

NA
:warning: Questions:
Tasks:
The following was done in the PR:
- Changed all the `.text-bg-*` occurrences in the docs
- Introduced documentation for Color and Background
- Uncommented some links
- Reviewed the wording a bit
- <https://deploy-preview-2831--boosted.netlify.app/docs/helpers/color-background>

[OUDS] Add color background helpers to the Colors tokens PR

---

js/tests/visual/dropdown.html
js/tests/visual/modal.html
js/tests/visual/scrollspy.html
scss/_variables.scss
scss/tokens/_raw.scss
site/assets/scss/_syntax.scss
site/content/docs/0.0/getting-started/accessibility.md
site/content/docs/0.0/helpers/icon.md
site/content/docs/0.0/migration-from-boosted.md
site/content/docs/0.0/migration.md
site/content/docs/0.0/utilities/borders.md
site/content/docs/0.0/utilities/position.md

NA
:warning: Questions:
Tasks:
The following was done in the PR:
- Added migrations guides.
- <https://deploy-preview-2838--boosted.netlify.app/docs/migration>
- <https://deploy-preview-2838--boosted.netlify.app/docs/migration-from-boosted>

[OUDS] Add migration guides to the color tokens PR

---

site/assets/scss/_boosted.scss
site/content/docs/5.3/accessibility-statement/_index.md

#2667 
Change font size, weight and centering on tables' captions
Accessibility audit reveled that captions looked too much as headings (very big by default) which can cause confusion
- <https://deploy-preview-2873--boosted.netlify.app/>

Fix a11y audit: change caption style on accessibility statement to comply to a11y

---

scss/_links.scss
scss/_root.scss

https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/issues/2893
To be align with Link component design

fix: link chevron disabled state

---

site/content/docs/0.3/forms/radio-button.md
site/content/docs/0.3/migration.md

closes #2946 
Add a second radio button in the invalid state example, require and enclose both in a `.was-validated` form to show the natural Invalid state via `:invalid` pseudo-class.
Design review
- <https://deploy-preview-2948--boosted.netlify.app/docs/0.3/forms/radio-button/#invalid>
- (NA) My new component is well displayed in [Storybook](https://deploy-preview-2948--boosted.netlify.app/storybook)
- (NA) Manually run …

[OUDS] Design review fix: invalid example with 2 radio buttons and was-validated

---

site/content/docs/0.3/forms/radio-button.md

closes #2947
Add a paragraph for outlined invalid Radio buttons
- <https://deploy-preview-2953--boosted.netlify.app/docs/0.3/forms/radio-button/#outlined-invalid>

doc: add a sub-paragraph for outlined invalid radio buttons

---

site/content/docs/0.3/forms/checkbox.md
site/content/docs/0.3/forms/radio-button.md
site/content/docs/0.3/forms/switch.md

closes #2954 
In addition to the work described in the issue, I fixed some redirects to control items.
- <https://deploy-preview-2955--boosted.netlify.app/>

[OUDS] display 2 controls with same config for all control items examples

---

site/content/docs/0.4/forms/checkbox.md
site/content/docs/0.4/forms/radio-button.md
site/content/docs/0.4/forms/switch.md
site/layouts/partials/callouts/input-invalid.md

closes #2961
- <https://deploy-preview-2964--boosted.netlify.app/docs/forms/checkbox/#invalid>
- x] I have read the [contributing guidelines](https://github.com/Orange-OpenSource/Orange-Boosted-Bootstrap/blob/main/.github/CONTRIBUTING.md)

docs: add info callout for invalid state

---

stories/create-stories-from-doc.js

NA
Remove folder auto before creating the stories of Storybook.
Avoiding to have fantom files in stories/auto.
- <https://deploy-preview-{your_pr_number}--boosted.netlify.app/storybook>

fix(storybook): remove directory when needed

---

site/content/docs/0.4/migration.md

closes #2999 
Change text bg color class on some elements in migration.md
We used the boostrap ones instead of OUDS'
- <https://deploy-preview-3011--boosted.netlify.app/>

[OUDS] docs use right bg color in migration md

---

site/content/docs/0.4/helpers/divider.md

Add Divider desigin guideline documentation link
Update Divider documentation page with a link to Divider Design Guideline documentation
Link design guideline documentation for developers
- Documentation
- <https://deploy-preview-3006--boosted.netlify.app/>

[OUDS] Docs: add divider design doc link

---

scss/_breadcrumb.scss
site/content/docs/0.4/components/breadcrumb.md

closes #3008
1. Add overflow hidden and no-wrap on last li of the breadcrumb
2. Add callout to note that the responsive part should not be used (too long titles)
3. Add titles on links
Breadcrumb was not displayed correctly with Bootstrap DOM. 
- <https://deploy-preview-3010--boosted.netlify.app/docs/components/breadcrumb/>

[OUDS] add title attibutes, bootstrap html handling and a callout on Breadcrumb

---

scss/forms/_control-item.scss

Closes #3019 
Removed the outline from the label to add it to the input itself.
Removed the padding and background-color from the label.
Be aligned with the design.
- <https://deploy-preview-3046--boosted.netlify.app/docs/forms/switch#standalone>

fix(switch): Standalone switch fix

---

site/src/scss/_tarteaucitron.scss

partially closes #2862
Move `display: none` on `.catToggleBtn`to its parent which also is a heading.
Removes the empty level 3 heading shown in HeadingsMap.
Remove cookies and open HeadingsMap, then click on "Personalize" in the cookie banner.
- <https://deploy-preview-3058--boosted.netlify.app/>

fix(tac): do not display category container at all

---

site/src/content/docs/components/back-to-top.mdx

Closes #3029
Use `{false}` instead of `"false"`.
Remove useless Back to top components- inside the documentation.
- <https://deploy-preview-3061--boosted.netlify.app/docs/components/back-to-top>

fix(docs): Update Back to top documentation to use jsx syntax

---

site/src/scss/_tarteaucitron.scss

closes #2862
Port https://github.com/AmauriC/tarteaucitron.js/commit/40e164c1c3795272e66904092d6b00f003075953 into our tarteaucitron custom Scss
This will hide the first h2 from tarteaucitron when the  Cookies management modal is open.
Open the cookies mgmt modal and HeadingsMap, there should be only one h2 for Cookies management panel
- <https://deploy-preview-3065--boosted.netlify.app/>

fix(tac): port tac fix for duplicated h2 into our scss

---

build/generate-sri.mjs
config.yml
js/index.esm.js
js/index.umd.js
package-lock.json
package.json
scss/_accordion.scss
scss/_button-group.scss
scss/_buttons.scss
scss/_carousel.scss
scss/_dropdown.scss
scss/_links.scss
scss/_list-group.scss
scss/_nav.scss
scss/_pagination.scss
scss/_reboot.scss
scss/_variables.scss
scss/forms/_form-range.scss
scss/forms/_quantity-selector.scss
scss/forms/_star-rating.scss
site/src/content/docs/getting-started/accessibility.mdx
site/src/content/docs/getting-started/contents.mdx
site/src/content/docs/getting-started/introduction.mdx
site/src/content/docs/migrations/migration-from-boosted.mdx
site/src/content/docs/migrations/migration.mdx
site/src/libs/config.ts
site/src/scss/_search.scss

Following #2929
Removed the focus-visible polyfill and all mentions.
Changed the Scss to adapt the new usage.
Be aligned with our supported browserlist.
Lightweight our bundle.
- Breaking change (fix or feature that would change existing functionality)
- <https://deploy-preview-3067--boosted.netlify.app/docs/getting-started/accessibility>
- <https://deploy-preview-3067--boosted.netlify.app/docs/getting-started/introduction>
- <https://deploy-preview-3067--boosted.netlify.app/docs/getting-started/contents>
- <https://deploy-preview-3067--boosted.netlify.app/migration>
- <https://deploy-preview-3067--boosted.netlify.app/migration-from-boosted>

feat(lib): remove focus-visible polyfill

---

site/src/scss/_component-examples.scss

Removes small margin at the bottom of code examples
- <https://deploy-preview-3119--boosted.netlify.app/>

fix(doc): remove bottom margin on code examples
